services:
  db:  # Service PostgreSQL database
    image: postgres:15  # Dùng image postgres phiên bản 15
    restart: always  # Tự động restart nếu container dừng bất ngờ
    env_file:
      - .env
    environment:  # Các biến môi trường khi khởi động DB
      POSTGRES_USER: ${DB_USER}  # Tên người dùng mặc định
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Mật khẩu cho user
      POSTGRES_DB: ${DB_NAME}  # Tên database khởi tạo sẵn
    ports:
      - "${DB_PORT}:${DB_PORT}"  # Mở port host → 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Gắn volume để lưu dữ liệu vĩnh viễn
      - ./resource/db/db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql
    networks:
      - homemie-net  # Nối vào mạng riêng tên "homemie-net"

  app:  # Service Go backend
    build:
      # context: ./docker/  # Build từ thư mục cha (giả sử Dockerfile nằm trong ./docker/)
      dockerfile: Dockerfile  # Tên file Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"  # Mở port 8080 (host) → 8080 (container)
    environment:  # Các biến môi trường backend cần để chạy
      DB_HOST: ${DB_HOST}  # Hostname của service db (Docker DNS sẽ tự nhận)
      DB_PORT: ${DB_PORT}  # Cổng PostgreSQL
      DB_USER: ${DB_USER}  # Username dùng kết nối DB
      DB_PASSWORD: ${DB_PASSWORD}  # Password kết nối DB
      DB_NAME: ${DB_NAME}  # Tên DB cần kết nối
      JWT_SECRET: ${JWT_SECRET}  # Secret key để mã hóa/giải mã JWT token
    depends_on:
      - db  # Đảm bảo container db khởi động trước
    networks:
      - homemie-net  # Gắn vào cùng mạng với db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - homemie-net

volumes:
  postgres_data:  # Khai báo volume để lưu trữ dữ liệu DB
  minio_data:

networks:
  homemie-net:  # Khai báo mạng riêng dùng cho các service trong hệ thống
