// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AdPackage is an object representing the database table.
type AdPackage struct {
	ID               int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name             string        `boil:"name" json:"name" toml:"name" yaml:"name"`
	DurationDays     int           `boil:"duration_days" json:"duration_days" toml:"duration_days" yaml:"duration_days"`
	Price            types.Decimal `boil:"price" json:"price" toml:"price" yaml:"price"`
	PriorityLevel    null.Int      `boil:"priority_level" json:"priority_level,omitempty" toml:"priority_level" yaml:"priority_level,omitempty"`
	DisplayLocations null.JSON     `boil:"display_locations" json:"display_locations,omitempty" toml:"display_locations" yaml:"display_locations,omitempty"`
	PromotedAreas    null.JSON     `boil:"promoted_areas" json:"promoted_areas,omitempty" toml:"promoted_areas" yaml:"promoted_areas,omitempty"`
	Description      null.String   `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	IsActive         null.Bool     `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	CreatedAt        null.Time     `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt        null.Time     `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *adPackageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L adPackageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AdPackageColumns = struct {
	ID               string
	Name             string
	DurationDays     string
	Price            string
	PriorityLevel    string
	DisplayLocations string
	PromotedAreas    string
	Description      string
	IsActive         string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "id",
	Name:             "name",
	DurationDays:     "duration_days",
	Price:            "price",
	PriorityLevel:    "priority_level",
	DisplayLocations: "display_locations",
	PromotedAreas:    "promoted_areas",
	Description:      "description",
	IsActive:         "is_active",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

var AdPackageTableColumns = struct {
	ID               string
	Name             string
	DurationDays     string
	Price            string
	PriorityLevel    string
	DisplayLocations string
	PromotedAreas    string
	Description      string
	IsActive         string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "ad_packages.id",
	Name:             "ad_packages.name",
	DurationDays:     "ad_packages.duration_days",
	Price:            "ad_packages.price",
	PriorityLevel:    "ad_packages.priority_level",
	DisplayLocations: "ad_packages.display_locations",
	PromotedAreas:    "ad_packages.promoted_areas",
	Description:      "ad_packages.description",
	IsActive:         "ad_packages.is_active",
	CreatedAt:        "ad_packages.created_at",
	UpdatedAt:        "ad_packages.updated_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Bool struct{ field string }

func (w whereHelpernull_Bool) EQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bool) NEQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bool) LT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bool) LTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bool) GT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bool) GTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bool) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bool) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var AdPackageWhere = struct {
	ID               whereHelperint64
	Name             whereHelperstring
	DurationDays     whereHelperint
	Price            whereHelpertypes_Decimal
	PriorityLevel    whereHelpernull_Int
	DisplayLocations whereHelpernull_JSON
	PromotedAreas    whereHelpernull_JSON
	Description      whereHelpernull_String
	IsActive         whereHelpernull_Bool
	CreatedAt        whereHelpernull_Time
	UpdatedAt        whereHelpernull_Time
}{
	ID:               whereHelperint64{field: "\"ad_packages\".\"id\""},
	Name:             whereHelperstring{field: "\"ad_packages\".\"name\""},
	DurationDays:     whereHelperint{field: "\"ad_packages\".\"duration_days\""},
	Price:            whereHelpertypes_Decimal{field: "\"ad_packages\".\"price\""},
	PriorityLevel:    whereHelpernull_Int{field: "\"ad_packages\".\"priority_level\""},
	DisplayLocations: whereHelpernull_JSON{field: "\"ad_packages\".\"display_locations\""},
	PromotedAreas:    whereHelpernull_JSON{field: "\"ad_packages\".\"promoted_areas\""},
	Description:      whereHelpernull_String{field: "\"ad_packages\".\"description\""},
	IsActive:         whereHelpernull_Bool{field: "\"ad_packages\".\"is_active\""},
	CreatedAt:        whereHelpernull_Time{field: "\"ad_packages\".\"created_at\""},
	UpdatedAt:        whereHelpernull_Time{field: "\"ad_packages\".\"updated_at\""},
}

// AdPackageRels is where relationship names are stored.
var AdPackageRels = struct {
	FeaturedAds string
}{
	FeaturedAds: "FeaturedAds",
}

// adPackageR is where relationships are stored.
type adPackageR struct {
	FeaturedAds FeaturedAdSlice `boil:"FeaturedAds" json:"FeaturedAds" toml:"FeaturedAds" yaml:"FeaturedAds"`
}

// NewStruct creates a new relationship struct
func (*adPackageR) NewStruct() *adPackageR {
	return &adPackageR{}
}

func (o *AdPackage) GetFeaturedAds() FeaturedAdSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFeaturedAds()
}

func (r *adPackageR) GetFeaturedAds() FeaturedAdSlice {
	if r == nil {
		return nil
	}

	return r.FeaturedAds
}

// adPackageL is where Load methods for each relationship are stored.
type adPackageL struct{}

var (
	adPackageAllColumns            = []string{"id", "name", "duration_days", "price", "priority_level", "display_locations", "promoted_areas", "description", "is_active", "created_at", "updated_at"}
	adPackageColumnsWithoutDefault = []string{"name", "duration_days", "price"}
	adPackageColumnsWithDefault    = []string{"id", "priority_level", "display_locations", "promoted_areas", "description", "is_active", "created_at", "updated_at"}
	adPackagePrimaryKeyColumns     = []string{"id"}
	adPackageGeneratedColumns      = []string{"id"}
)

type (
	// AdPackageSlice is an alias for a slice of pointers to AdPackage.
	// This should almost always be used instead of []AdPackage.
	AdPackageSlice []*AdPackage
	// AdPackageHook is the signature for custom AdPackage hook methods
	AdPackageHook func(context.Context, boil.ContextExecutor, *AdPackage) error

	adPackageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	adPackageType                 = reflect.TypeOf(&AdPackage{})
	adPackageMapping              = queries.MakeStructMapping(adPackageType)
	adPackagePrimaryKeyMapping, _ = queries.BindMapping(adPackageType, adPackageMapping, adPackagePrimaryKeyColumns)
	adPackageInsertCacheMut       sync.RWMutex
	adPackageInsertCache          = make(map[string]insertCache)
	adPackageUpdateCacheMut       sync.RWMutex
	adPackageUpdateCache          = make(map[string]updateCache)
	adPackageUpsertCacheMut       sync.RWMutex
	adPackageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var adPackageAfterSelectMu sync.Mutex
var adPackageAfterSelectHooks []AdPackageHook

var adPackageBeforeInsertMu sync.Mutex
var adPackageBeforeInsertHooks []AdPackageHook
var adPackageAfterInsertMu sync.Mutex
var adPackageAfterInsertHooks []AdPackageHook

var adPackageBeforeUpdateMu sync.Mutex
var adPackageBeforeUpdateHooks []AdPackageHook
var adPackageAfterUpdateMu sync.Mutex
var adPackageAfterUpdateHooks []AdPackageHook

var adPackageBeforeDeleteMu sync.Mutex
var adPackageBeforeDeleteHooks []AdPackageHook
var adPackageAfterDeleteMu sync.Mutex
var adPackageAfterDeleteHooks []AdPackageHook

var adPackageBeforeUpsertMu sync.Mutex
var adPackageBeforeUpsertHooks []AdPackageHook
var adPackageAfterUpsertMu sync.Mutex
var adPackageAfterUpsertHooks []AdPackageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AdPackage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AdPackage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AdPackage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AdPackage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AdPackage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AdPackage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AdPackage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AdPackage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AdPackage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range adPackageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAdPackageHook registers your hook function for all future operations.
func AddAdPackageHook(hookPoint boil.HookPoint, adPackageHook AdPackageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		adPackageAfterSelectMu.Lock()
		adPackageAfterSelectHooks = append(adPackageAfterSelectHooks, adPackageHook)
		adPackageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		adPackageBeforeInsertMu.Lock()
		adPackageBeforeInsertHooks = append(adPackageBeforeInsertHooks, adPackageHook)
		adPackageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		adPackageAfterInsertMu.Lock()
		adPackageAfterInsertHooks = append(adPackageAfterInsertHooks, adPackageHook)
		adPackageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		adPackageBeforeUpdateMu.Lock()
		adPackageBeforeUpdateHooks = append(adPackageBeforeUpdateHooks, adPackageHook)
		adPackageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		adPackageAfterUpdateMu.Lock()
		adPackageAfterUpdateHooks = append(adPackageAfterUpdateHooks, adPackageHook)
		adPackageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		adPackageBeforeDeleteMu.Lock()
		adPackageBeforeDeleteHooks = append(adPackageBeforeDeleteHooks, adPackageHook)
		adPackageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		adPackageAfterDeleteMu.Lock()
		adPackageAfterDeleteHooks = append(adPackageAfterDeleteHooks, adPackageHook)
		adPackageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		adPackageBeforeUpsertMu.Lock()
		adPackageBeforeUpsertHooks = append(adPackageBeforeUpsertHooks, adPackageHook)
		adPackageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		adPackageAfterUpsertMu.Lock()
		adPackageAfterUpsertHooks = append(adPackageAfterUpsertHooks, adPackageHook)
		adPackageAfterUpsertMu.Unlock()
	}
}

// One returns a single adPackage record from the query.
func (q adPackageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AdPackage, error) {
	o := &AdPackage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for ad_packages")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AdPackage records from the query.
func (q adPackageQuery) All(ctx context.Context, exec boil.ContextExecutor) (AdPackageSlice, error) {
	var o []*AdPackage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AdPackage slice")
	}

	if len(adPackageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AdPackage records in the query.
func (q adPackageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count ad_packages rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q adPackageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if ad_packages exists")
	}

	return count > 0, nil
}

// FeaturedAds retrieves all the featured_ad's FeaturedAds with an executor.
func (o *AdPackage) FeaturedAds(mods ...qm.QueryMod) featuredAdQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"featured_ads\".\"ad_package_id\"=?", o.ID),
	)

	return FeaturedAds(queryMods...)
}

// LoadFeaturedAds allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (adPackageL) LoadFeaturedAds(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAdPackage interface{}, mods queries.Applicator) error {
	var slice []*AdPackage
	var object *AdPackage

	if singular {
		var ok bool
		object, ok = maybeAdPackage.(*AdPackage)
		if !ok {
			object = new(AdPackage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAdPackage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAdPackage))
			}
		}
	} else {
		s, ok := maybeAdPackage.(*[]*AdPackage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAdPackage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAdPackage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &adPackageR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &adPackageR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`featured_ads`),
		qm.WhereIn(`featured_ads.ad_package_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load featured_ads")
	}

	var resultSlice []*FeaturedAd
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice featured_ads")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on featured_ads")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for featured_ads")
	}

	if len(featuredAdAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FeaturedAds = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &featuredAdR{}
			}
			foreign.R.AdPackage = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AdPackageID) {
				local.R.FeaturedAds = append(local.R.FeaturedAds, foreign)
				if foreign.R == nil {
					foreign.R = &featuredAdR{}
				}
				foreign.R.AdPackage = local
				break
			}
		}
	}

	return nil
}

// AddFeaturedAds adds the given related objects to the existing relationships
// of the ad_package, optionally inserting them as new records.
// Appends related to o.R.FeaturedAds.
// Sets related.R.AdPackage appropriately.
func (o *AdPackage) AddFeaturedAds(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*FeaturedAd) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AdPackageID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"featured_ads\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"ad_package_id"}),
				strmangle.WhereClause("\"", "\"", 2, featuredAdPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AdPackageID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &adPackageR{
			FeaturedAds: related,
		}
	} else {
		o.R.FeaturedAds = append(o.R.FeaturedAds, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &featuredAdR{
				AdPackage: o,
			}
		} else {
			rel.R.AdPackage = o
		}
	}
	return nil
}

// SetFeaturedAds removes all previously related items of the
// ad_package replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.AdPackage's FeaturedAds accordingly.
// Replaces o.R.FeaturedAds with related.
// Sets related.R.AdPackage's FeaturedAds accordingly.
func (o *AdPackage) SetFeaturedAds(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*FeaturedAd) error {
	query := "update \"featured_ads\" set \"ad_package_id\" = null where \"ad_package_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.FeaturedAds {
			queries.SetScanner(&rel.AdPackageID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.AdPackage = nil
		}
		o.R.FeaturedAds = nil
	}

	return o.AddFeaturedAds(ctx, exec, insert, related...)
}

// RemoveFeaturedAds relationships from objects passed in.
// Removes related items from R.FeaturedAds (uses pointer comparison, removal does not keep order)
// Sets related.R.AdPackage.
func (o *AdPackage) RemoveFeaturedAds(ctx context.Context, exec boil.ContextExecutor, related ...*FeaturedAd) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AdPackageID, nil)
		if rel.R != nil {
			rel.R.AdPackage = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("ad_package_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.FeaturedAds {
			if rel != ri {
				continue
			}

			ln := len(o.R.FeaturedAds)
			if ln > 1 && i < ln-1 {
				o.R.FeaturedAds[i] = o.R.FeaturedAds[ln-1]
			}
			o.R.FeaturedAds = o.R.FeaturedAds[:ln-1]
			break
		}
	}

	return nil
}

// AdPackages retrieves all the records using an executor.
func AdPackages(mods ...qm.QueryMod) adPackageQuery {
	mods = append(mods, qm.From("\"ad_packages\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ad_packages\".*"})
	}

	return adPackageQuery{q}
}

// FindAdPackage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAdPackage(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*AdPackage, error) {
	adPackageObj := &AdPackage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ad_packages\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, adPackageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from ad_packages")
	}

	if err = adPackageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return adPackageObj, err
	}

	return adPackageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AdPackage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ad_packages provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(adPackageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	adPackageInsertCacheMut.RLock()
	cache, cached := adPackageInsertCache[key]
	adPackageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			adPackageAllColumns,
			adPackageColumnsWithDefault,
			adPackageColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, adPackageGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(adPackageType, adPackageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(adPackageType, adPackageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ad_packages\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ad_packages\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into ad_packages")
	}

	if !cached {
		adPackageInsertCacheMut.Lock()
		adPackageInsertCache[key] = cache
		adPackageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AdPackage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AdPackage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	adPackageUpdateCacheMut.RLock()
	cache, cached := adPackageUpdateCache[key]
	adPackageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			adPackageAllColumns,
			adPackagePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, adPackageGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update ad_packages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ad_packages\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, adPackagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(adPackageType, adPackageMapping, append(wl, adPackagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update ad_packages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for ad_packages")
	}

	if !cached {
		adPackageUpdateCacheMut.Lock()
		adPackageUpdateCache[key] = cache
		adPackageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q adPackageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for ad_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for ad_packages")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AdPackageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), adPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ad_packages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, adPackagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in adPackage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all adPackage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AdPackage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no ad_packages provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(adPackageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	adPackageUpsertCacheMut.RLock()
	cache, cached := adPackageUpsertCache[key]
	adPackageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			adPackageAllColumns,
			adPackageColumnsWithDefault,
			adPackageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			adPackageAllColumns,
			adPackagePrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, adPackageGeneratedColumns)
		update = strmangle.SetComplement(update, adPackageGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert ad_packages, could not build update column list")
		}

		ret := strmangle.SetComplement(adPackageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(adPackagePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert ad_packages, could not build conflict column list")
			}

			conflict = make([]string, len(adPackagePrimaryKeyColumns))
			copy(conflict, adPackagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ad_packages\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(adPackageType, adPackageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(adPackageType, adPackageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert ad_packages")
	}

	if !cached {
		adPackageUpsertCacheMut.Lock()
		adPackageUpsertCache[key] = cache
		adPackageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AdPackage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AdPackage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AdPackage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), adPackagePrimaryKeyMapping)
	sql := "DELETE FROM \"ad_packages\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from ad_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for ad_packages")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q adPackageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no adPackageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ad_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ad_packages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AdPackageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(adPackageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), adPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ad_packages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, adPackagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from adPackage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ad_packages")
	}

	if len(adPackageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AdPackage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAdPackage(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AdPackageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AdPackageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), adPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ad_packages\".* FROM \"ad_packages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, adPackagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AdPackageSlice")
	}

	*o = slice

	return nil
}

// AdPackageExists checks if the AdPackage row exists.
func AdPackageExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ad_packages\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if ad_packages exists")
	}

	return exists, nil
}

// Exists checks if the AdPackage row exists.
func (o *AdPackage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AdPackageExists(ctx, exec, o.ID)
}
