// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AddressLocation is an object representing the database table.
type AddressLocation struct {
	ID       int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name     string     `boil:"name" json:"name" toml:"name" yaml:"name"`
	Level    string     `boil:"level" json:"level" toml:"level" yaml:"level"`
	ParentID null.Int64 `boil:"parent_id" json:"parent_id,omitempty" toml:"parent_id" yaml:"parent_id,omitempty"`

	R *addressLocationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L addressLocationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AddressLocationColumns = struct {
	ID       string
	Name     string
	Level    string
	ParentID string
}{
	ID:       "id",
	Name:     "name",
	Level:    "level",
	ParentID: "parent_id",
}

var AddressLocationTableColumns = struct {
	ID       string
	Name     string
	Level    string
	ParentID string
}{
	ID:       "address_locations.id",
	Name:     "address_locations.name",
	Level:    "address_locations.level",
	ParentID: "address_locations.parent_id",
}

// Generated where

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var AddressLocationWhere = struct {
	ID       whereHelperint64
	Name     whereHelperstring
	Level    whereHelperstring
	ParentID whereHelpernull_Int64
}{
	ID:       whereHelperint64{field: "\"address_locations\".\"id\""},
	Name:     whereHelperstring{field: "\"address_locations\".\"name\""},
	Level:    whereHelperstring{field: "\"address_locations\".\"level\""},
	ParentID: whereHelpernull_Int64{field: "\"address_locations\".\"parent_id\""},
}

// AddressLocationRels is where relationship names are stored.
var AddressLocationRels = struct {
	Parent                 string
	ParentAddressLocations string
	AreaAddresses          string
	CityAddresses          string
	WardAddresses          string
}{
	Parent:                 "Parent",
	ParentAddressLocations: "ParentAddressLocations",
	AreaAddresses:          "AreaAddresses",
	CityAddresses:          "CityAddresses",
	WardAddresses:          "WardAddresses",
}

// addressLocationR is where relationships are stored.
type addressLocationR struct {
	Parent                 *AddressLocation     `boil:"Parent" json:"Parent" toml:"Parent" yaml:"Parent"`
	ParentAddressLocations AddressLocationSlice `boil:"ParentAddressLocations" json:"ParentAddressLocations" toml:"ParentAddressLocations" yaml:"ParentAddressLocations"`
	AreaAddresses          AddressSlice         `boil:"AreaAddresses" json:"AreaAddresses" toml:"AreaAddresses" yaml:"AreaAddresses"`
	CityAddresses          AddressSlice         `boil:"CityAddresses" json:"CityAddresses" toml:"CityAddresses" yaml:"CityAddresses"`
	WardAddresses          AddressSlice         `boil:"WardAddresses" json:"WardAddresses" toml:"WardAddresses" yaml:"WardAddresses"`
}

// NewStruct creates a new relationship struct
func (*addressLocationR) NewStruct() *addressLocationR {
	return &addressLocationR{}
}

func (o *AddressLocation) GetParent() *AddressLocation {
	if o == nil {
		return nil
	}

	return o.R.GetParent()
}

func (r *addressLocationR) GetParent() *AddressLocation {
	if r == nil {
		return nil
	}

	return r.Parent
}

func (o *AddressLocation) GetParentAddressLocations() AddressLocationSlice {
	if o == nil {
		return nil
	}

	return o.R.GetParentAddressLocations()
}

func (r *addressLocationR) GetParentAddressLocations() AddressLocationSlice {
	if r == nil {
		return nil
	}

	return r.ParentAddressLocations
}

func (o *AddressLocation) GetAreaAddresses() AddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAreaAddresses()
}

func (r *addressLocationR) GetAreaAddresses() AddressSlice {
	if r == nil {
		return nil
	}

	return r.AreaAddresses
}

func (o *AddressLocation) GetCityAddresses() AddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCityAddresses()
}

func (r *addressLocationR) GetCityAddresses() AddressSlice {
	if r == nil {
		return nil
	}

	return r.CityAddresses
}

func (o *AddressLocation) GetWardAddresses() AddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWardAddresses()
}

func (r *addressLocationR) GetWardAddresses() AddressSlice {
	if r == nil {
		return nil
	}

	return r.WardAddresses
}

// addressLocationL is where Load methods for each relationship are stored.
type addressLocationL struct{}

var (
	addressLocationAllColumns            = []string{"id", "name", "level", "parent_id"}
	addressLocationColumnsWithoutDefault = []string{"name", "level"}
	addressLocationColumnsWithDefault    = []string{"id", "parent_id"}
	addressLocationPrimaryKeyColumns     = []string{"id"}
	addressLocationGeneratedColumns      = []string{"id"}
)

type (
	// AddressLocationSlice is an alias for a slice of pointers to AddressLocation.
	// This should almost always be used instead of []AddressLocation.
	AddressLocationSlice []*AddressLocation
	// AddressLocationHook is the signature for custom AddressLocation hook methods
	AddressLocationHook func(context.Context, boil.ContextExecutor, *AddressLocation) error

	addressLocationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	addressLocationType                 = reflect.TypeOf(&AddressLocation{})
	addressLocationMapping              = queries.MakeStructMapping(addressLocationType)
	addressLocationPrimaryKeyMapping, _ = queries.BindMapping(addressLocationType, addressLocationMapping, addressLocationPrimaryKeyColumns)
	addressLocationInsertCacheMut       sync.RWMutex
	addressLocationInsertCache          = make(map[string]insertCache)
	addressLocationUpdateCacheMut       sync.RWMutex
	addressLocationUpdateCache          = make(map[string]updateCache)
	addressLocationUpsertCacheMut       sync.RWMutex
	addressLocationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var addressLocationAfterSelectMu sync.Mutex
var addressLocationAfterSelectHooks []AddressLocationHook

var addressLocationBeforeInsertMu sync.Mutex
var addressLocationBeforeInsertHooks []AddressLocationHook
var addressLocationAfterInsertMu sync.Mutex
var addressLocationAfterInsertHooks []AddressLocationHook

var addressLocationBeforeUpdateMu sync.Mutex
var addressLocationBeforeUpdateHooks []AddressLocationHook
var addressLocationAfterUpdateMu sync.Mutex
var addressLocationAfterUpdateHooks []AddressLocationHook

var addressLocationBeforeDeleteMu sync.Mutex
var addressLocationBeforeDeleteHooks []AddressLocationHook
var addressLocationAfterDeleteMu sync.Mutex
var addressLocationAfterDeleteHooks []AddressLocationHook

var addressLocationBeforeUpsertMu sync.Mutex
var addressLocationBeforeUpsertHooks []AddressLocationHook
var addressLocationAfterUpsertMu sync.Mutex
var addressLocationAfterUpsertHooks []AddressLocationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AddressLocation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AddressLocation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AddressLocation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AddressLocation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AddressLocation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AddressLocation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AddressLocation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AddressLocation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AddressLocation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range addressLocationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAddressLocationHook registers your hook function for all future operations.
func AddAddressLocationHook(hookPoint boil.HookPoint, addressLocationHook AddressLocationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		addressLocationAfterSelectMu.Lock()
		addressLocationAfterSelectHooks = append(addressLocationAfterSelectHooks, addressLocationHook)
		addressLocationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		addressLocationBeforeInsertMu.Lock()
		addressLocationBeforeInsertHooks = append(addressLocationBeforeInsertHooks, addressLocationHook)
		addressLocationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		addressLocationAfterInsertMu.Lock()
		addressLocationAfterInsertHooks = append(addressLocationAfterInsertHooks, addressLocationHook)
		addressLocationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		addressLocationBeforeUpdateMu.Lock()
		addressLocationBeforeUpdateHooks = append(addressLocationBeforeUpdateHooks, addressLocationHook)
		addressLocationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		addressLocationAfterUpdateMu.Lock()
		addressLocationAfterUpdateHooks = append(addressLocationAfterUpdateHooks, addressLocationHook)
		addressLocationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		addressLocationBeforeDeleteMu.Lock()
		addressLocationBeforeDeleteHooks = append(addressLocationBeforeDeleteHooks, addressLocationHook)
		addressLocationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		addressLocationAfterDeleteMu.Lock()
		addressLocationAfterDeleteHooks = append(addressLocationAfterDeleteHooks, addressLocationHook)
		addressLocationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		addressLocationBeforeUpsertMu.Lock()
		addressLocationBeforeUpsertHooks = append(addressLocationBeforeUpsertHooks, addressLocationHook)
		addressLocationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		addressLocationAfterUpsertMu.Lock()
		addressLocationAfterUpsertHooks = append(addressLocationAfterUpsertHooks, addressLocationHook)
		addressLocationAfterUpsertMu.Unlock()
	}
}

// One returns a single addressLocation record from the query.
func (q addressLocationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AddressLocation, error) {
	o := &AddressLocation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for address_locations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AddressLocation records from the query.
func (q addressLocationQuery) All(ctx context.Context, exec boil.ContextExecutor) (AddressLocationSlice, error) {
	var o []*AddressLocation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AddressLocation slice")
	}

	if len(addressLocationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AddressLocation records in the query.
func (q addressLocationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count address_locations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q addressLocationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if address_locations exists")
	}

	return count > 0, nil
}

// Parent pointed to by the foreign key.
func (o *AddressLocation) Parent(mods ...qm.QueryMod) addressLocationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParentID),
	}

	queryMods = append(queryMods, mods...)

	return AddressLocations(queryMods...)
}

// ParentAddressLocations retrieves all the address_location's AddressLocations with an executor via parent_id column.
func (o *AddressLocation) ParentAddressLocations(mods ...qm.QueryMod) addressLocationQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"address_locations\".\"parent_id\"=?", o.ID),
	)

	return AddressLocations(queryMods...)
}

// AreaAddresses retrieves all the address's Addresses with an executor via area_id column.
func (o *AddressLocation) AreaAddresses(mods ...qm.QueryMod) addressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"addresses\".\"area_id\"=?", o.ID),
	)

	return Addresses(queryMods...)
}

// CityAddresses retrieves all the address's Addresses with an executor via city_id column.
func (o *AddressLocation) CityAddresses(mods ...qm.QueryMod) addressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"addresses\".\"city_id\"=?", o.ID),
	)

	return Addresses(queryMods...)
}

// WardAddresses retrieves all the address's Addresses with an executor via ward_id column.
func (o *AddressLocation) WardAddresses(mods ...qm.QueryMod) addressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"addresses\".\"ward_id\"=?", o.ID),
	)

	return Addresses(queryMods...)
}

// LoadParent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (addressLocationL) LoadParent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAddressLocation interface{}, mods queries.Applicator) error {
	var slice []*AddressLocation
	var object *AddressLocation

	if singular {
		var ok bool
		object, ok = maybeAddressLocation.(*AddressLocation)
		if !ok {
			object = new(AddressLocation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAddressLocation))
			}
		}
	} else {
		s, ok := maybeAddressLocation.(*[]*AddressLocation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAddressLocation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &addressLocationR{}
		}
		if !queries.IsNil(object.ParentID) {
			args[object.ParentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &addressLocationR{}
			}

			if !queries.IsNil(obj.ParentID) {
				args[obj.ParentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`address_locations`),
		qm.WhereIn(`address_locations.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AddressLocation")
	}

	var resultSlice []*AddressLocation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AddressLocation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for address_locations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for address_locations")
	}

	if len(addressLocationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Parent = foreign
		if foreign.R == nil {
			foreign.R = &addressLocationR{}
		}
		foreign.R.ParentAddressLocations = append(foreign.R.ParentAddressLocations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ParentID, foreign.ID) {
				local.R.Parent = foreign
				if foreign.R == nil {
					foreign.R = &addressLocationR{}
				}
				foreign.R.ParentAddressLocations = append(foreign.R.ParentAddressLocations, local)
				break
			}
		}
	}

	return nil
}

// LoadParentAddressLocations allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (addressLocationL) LoadParentAddressLocations(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAddressLocation interface{}, mods queries.Applicator) error {
	var slice []*AddressLocation
	var object *AddressLocation

	if singular {
		var ok bool
		object, ok = maybeAddressLocation.(*AddressLocation)
		if !ok {
			object = new(AddressLocation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAddressLocation))
			}
		}
	} else {
		s, ok := maybeAddressLocation.(*[]*AddressLocation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAddressLocation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &addressLocationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &addressLocationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`address_locations`),
		qm.WhereIn(`address_locations.parent_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load address_locations")
	}

	var resultSlice []*AddressLocation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice address_locations")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on address_locations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for address_locations")
	}

	if len(addressLocationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParentAddressLocations = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &addressLocationR{}
			}
			foreign.R.Parent = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ParentID) {
				local.R.ParentAddressLocations = append(local.R.ParentAddressLocations, foreign)
				if foreign.R == nil {
					foreign.R = &addressLocationR{}
				}
				foreign.R.Parent = local
				break
			}
		}
	}

	return nil
}

// LoadAreaAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (addressLocationL) LoadAreaAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAddressLocation interface{}, mods queries.Applicator) error {
	var slice []*AddressLocation
	var object *AddressLocation

	if singular {
		var ok bool
		object, ok = maybeAddressLocation.(*AddressLocation)
		if !ok {
			object = new(AddressLocation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAddressLocation))
			}
		}
	} else {
		s, ok := maybeAddressLocation.(*[]*AddressLocation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAddressLocation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &addressLocationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &addressLocationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`addresses`),
		qm.WhereIn(`addresses.area_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load addresses")
	}

	var resultSlice []*Address
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for addresses")
	}

	if len(addressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.AreaAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &addressR{}
			}
			foreign.R.Area = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AreaID) {
				local.R.AreaAddresses = append(local.R.AreaAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &addressR{}
				}
				foreign.R.Area = local
				break
			}
		}
	}

	return nil
}

// LoadCityAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (addressLocationL) LoadCityAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAddressLocation interface{}, mods queries.Applicator) error {
	var slice []*AddressLocation
	var object *AddressLocation

	if singular {
		var ok bool
		object, ok = maybeAddressLocation.(*AddressLocation)
		if !ok {
			object = new(AddressLocation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAddressLocation))
			}
		}
	} else {
		s, ok := maybeAddressLocation.(*[]*AddressLocation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAddressLocation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &addressLocationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &addressLocationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`addresses`),
		qm.WhereIn(`addresses.city_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load addresses")
	}

	var resultSlice []*Address
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for addresses")
	}

	if len(addressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CityAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &addressR{}
			}
			foreign.R.City = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.CityID {
				local.R.CityAddresses = append(local.R.CityAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &addressR{}
				}
				foreign.R.City = local
				break
			}
		}
	}

	return nil
}

// LoadWardAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (addressLocationL) LoadWardAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAddressLocation interface{}, mods queries.Applicator) error {
	var slice []*AddressLocation
	var object *AddressLocation

	if singular {
		var ok bool
		object, ok = maybeAddressLocation.(*AddressLocation)
		if !ok {
			object = new(AddressLocation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAddressLocation))
			}
		}
	} else {
		s, ok := maybeAddressLocation.(*[]*AddressLocation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAddressLocation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAddressLocation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &addressLocationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &addressLocationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`addresses`),
		qm.WhereIn(`addresses.ward_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load addresses")
	}

	var resultSlice []*Address
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for addresses")
	}

	if len(addressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WardAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &addressR{}
			}
			foreign.R.Ward = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WardID {
				local.R.WardAddresses = append(local.R.WardAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &addressR{}
				}
				foreign.R.Ward = local
				break
			}
		}
	}

	return nil
}

// SetParent of the addressLocation to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentAddressLocations.
func (o *AddressLocation) SetParent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AddressLocation) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"address_locations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
		strmangle.WhereClause("\"", "\"", 2, addressLocationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ParentID, related.ID)
	if o.R == nil {
		o.R = &addressLocationR{
			Parent: related,
		}
	} else {
		o.R.Parent = related
	}

	if related.R == nil {
		related.R = &addressLocationR{
			ParentAddressLocations: AddressLocationSlice{o},
		}
	} else {
		related.R.ParentAddressLocations = append(related.R.ParentAddressLocations, o)
	}

	return nil
}

// RemoveParent relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *AddressLocation) RemoveParent(ctx context.Context, exec boil.ContextExecutor, related *AddressLocation) error {
	var err error

	queries.SetScanner(&o.ParentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Parent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ParentAddressLocations {
		if queries.Equal(o.ParentID, ri.ParentID) {
			continue
		}

		ln := len(related.R.ParentAddressLocations)
		if ln > 1 && i < ln-1 {
			related.R.ParentAddressLocations[i] = related.R.ParentAddressLocations[ln-1]
		}
		related.R.ParentAddressLocations = related.R.ParentAddressLocations[:ln-1]
		break
	}
	return nil
}

// AddParentAddressLocations adds the given related objects to the existing relationships
// of the address_location, optionally inserting them as new records.
// Appends related to o.R.ParentAddressLocations.
// Sets related.R.Parent appropriately.
func (o *AddressLocation) AddParentAddressLocations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AddressLocation) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ParentID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"address_locations\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
				strmangle.WhereClause("\"", "\"", 2, addressLocationPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ParentID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &addressLocationR{
			ParentAddressLocations: related,
		}
	} else {
		o.R.ParentAddressLocations = append(o.R.ParentAddressLocations, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &addressLocationR{
				Parent: o,
			}
		} else {
			rel.R.Parent = o
		}
	}
	return nil
}

// SetParentAddressLocations removes all previously related items of the
// address_location replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentAddressLocations accordingly.
// Replaces o.R.ParentAddressLocations with related.
// Sets related.R.Parent's ParentAddressLocations accordingly.
func (o *AddressLocation) SetParentAddressLocations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AddressLocation) error {
	query := "update \"address_locations\" set \"parent_id\" = null where \"parent_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ParentAddressLocations {
			queries.SetScanner(&rel.ParentID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Parent = nil
		}
		o.R.ParentAddressLocations = nil
	}

	return o.AddParentAddressLocations(ctx, exec, insert, related...)
}

// RemoveParentAddressLocations relationships from objects passed in.
// Removes related items from R.ParentAddressLocations (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
func (o *AddressLocation) RemoveParentAddressLocations(ctx context.Context, exec boil.ContextExecutor, related ...*AddressLocation) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ParentID, nil)
		if rel.R != nil {
			rel.R.Parent = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentAddressLocations {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentAddressLocations)
			if ln > 1 && i < ln-1 {
				o.R.ParentAddressLocations[i] = o.R.ParentAddressLocations[ln-1]
			}
			o.R.ParentAddressLocations = o.R.ParentAddressLocations[:ln-1]
			break
		}
	}

	return nil
}

// AddAreaAddresses adds the given related objects to the existing relationships
// of the address_location, optionally inserting them as new records.
// Appends related to o.R.AreaAddresses.
// Sets related.R.Area appropriately.
func (o *AddressLocation) AddAreaAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Address) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AreaID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"area_id"}),
				strmangle.WhereClause("\"", "\"", 2, addressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AreaID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &addressLocationR{
			AreaAddresses: related,
		}
	} else {
		o.R.AreaAddresses = append(o.R.AreaAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &addressR{
				Area: o,
			}
		} else {
			rel.R.Area = o
		}
	}
	return nil
}

// SetAreaAddresses removes all previously related items of the
// address_location replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Area's AreaAddresses accordingly.
// Replaces o.R.AreaAddresses with related.
// Sets related.R.Area's AreaAddresses accordingly.
func (o *AddressLocation) SetAreaAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Address) error {
	query := "update \"addresses\" set \"area_id\" = null where \"area_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.AreaAddresses {
			queries.SetScanner(&rel.AreaID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Area = nil
		}
		o.R.AreaAddresses = nil
	}

	return o.AddAreaAddresses(ctx, exec, insert, related...)
}

// RemoveAreaAddresses relationships from objects passed in.
// Removes related items from R.AreaAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.Area.
func (o *AddressLocation) RemoveAreaAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*Address) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AreaID, nil)
		if rel.R != nil {
			rel.R.Area = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("area_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.AreaAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.AreaAddresses)
			if ln > 1 && i < ln-1 {
				o.R.AreaAddresses[i] = o.R.AreaAddresses[ln-1]
			}
			o.R.AreaAddresses = o.R.AreaAddresses[:ln-1]
			break
		}
	}

	return nil
}

// AddCityAddresses adds the given related objects to the existing relationships
// of the address_location, optionally inserting them as new records.
// Appends related to o.R.CityAddresses.
// Sets related.R.City appropriately.
func (o *AddressLocation) AddCityAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Address) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CityID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"city_id"}),
				strmangle.WhereClause("\"", "\"", 2, addressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CityID = o.ID
		}
	}

	if o.R == nil {
		o.R = &addressLocationR{
			CityAddresses: related,
		}
	} else {
		o.R.CityAddresses = append(o.R.CityAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &addressR{
				City: o,
			}
		} else {
			rel.R.City = o
		}
	}
	return nil
}

// AddWardAddresses adds the given related objects to the existing relationships
// of the address_location, optionally inserting them as new records.
// Appends related to o.R.WardAddresses.
// Sets related.R.Ward appropriately.
func (o *AddressLocation) AddWardAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Address) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WardID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"ward_id"}),
				strmangle.WhereClause("\"", "\"", 2, addressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WardID = o.ID
		}
	}

	if o.R == nil {
		o.R = &addressLocationR{
			WardAddresses: related,
		}
	} else {
		o.R.WardAddresses = append(o.R.WardAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &addressR{
				Ward: o,
			}
		} else {
			rel.R.Ward = o
		}
	}
	return nil
}

// AddressLocations retrieves all the records using an executor.
func AddressLocations(mods ...qm.QueryMod) addressLocationQuery {
	mods = append(mods, qm.From("\"address_locations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"address_locations\".*"})
	}

	return addressLocationQuery{q}
}

// FindAddressLocation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAddressLocation(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*AddressLocation, error) {
	addressLocationObj := &AddressLocation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"address_locations\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, addressLocationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from address_locations")
	}

	if err = addressLocationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return addressLocationObj, err
	}

	return addressLocationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AddressLocation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no address_locations provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(addressLocationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	addressLocationInsertCacheMut.RLock()
	cache, cached := addressLocationInsertCache[key]
	addressLocationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			addressLocationAllColumns,
			addressLocationColumnsWithDefault,
			addressLocationColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, addressLocationGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(addressLocationType, addressLocationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(addressLocationType, addressLocationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"address_locations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"address_locations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into address_locations")
	}

	if !cached {
		addressLocationInsertCacheMut.Lock()
		addressLocationInsertCache[key] = cache
		addressLocationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AddressLocation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AddressLocation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	addressLocationUpdateCacheMut.RLock()
	cache, cached := addressLocationUpdateCache[key]
	addressLocationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			addressLocationAllColumns,
			addressLocationPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, addressLocationGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update address_locations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"address_locations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, addressLocationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(addressLocationType, addressLocationMapping, append(wl, addressLocationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update address_locations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for address_locations")
	}

	if !cached {
		addressLocationUpdateCacheMut.Lock()
		addressLocationUpdateCache[key] = cache
		addressLocationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q addressLocationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for address_locations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for address_locations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AddressLocationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), addressLocationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"address_locations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, addressLocationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in addressLocation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all addressLocation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AddressLocation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no address_locations provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(addressLocationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	addressLocationUpsertCacheMut.RLock()
	cache, cached := addressLocationUpsertCache[key]
	addressLocationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			addressLocationAllColumns,
			addressLocationColumnsWithDefault,
			addressLocationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			addressLocationAllColumns,
			addressLocationPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, addressLocationGeneratedColumns)
		update = strmangle.SetComplement(update, addressLocationGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert address_locations, could not build update column list")
		}

		ret := strmangle.SetComplement(addressLocationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(addressLocationPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert address_locations, could not build conflict column list")
			}

			conflict = make([]string, len(addressLocationPrimaryKeyColumns))
			copy(conflict, addressLocationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"address_locations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(addressLocationType, addressLocationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(addressLocationType, addressLocationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert address_locations")
	}

	if !cached {
		addressLocationUpsertCacheMut.Lock()
		addressLocationUpsertCache[key] = cache
		addressLocationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AddressLocation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AddressLocation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AddressLocation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), addressLocationPrimaryKeyMapping)
	sql := "DELETE FROM \"address_locations\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from address_locations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for address_locations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q addressLocationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no addressLocationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from address_locations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for address_locations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AddressLocationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(addressLocationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), addressLocationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"address_locations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, addressLocationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from addressLocation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for address_locations")
	}

	if len(addressLocationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AddressLocation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAddressLocation(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AddressLocationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AddressLocationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), addressLocationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"address_locations\".* FROM \"address_locations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, addressLocationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AddressLocationSlice")
	}

	*o = slice

	return nil
}

// AddressLocationExists checks if the AddressLocation row exists.
func AddressLocationExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"address_locations\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if address_locations exists")
	}

	return exists, nil
}

// Exists checks if the AddressLocation row exists.
func (o *AddressLocation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AddressLocationExists(ctx, exec, o.ID)
}
