// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Booking is an object representing the database table.
type Booking struct {
	ID                       int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	ListingID                int64       `boil:"listing_id" json:"listing_id" toml:"listing_id" yaml:"listing_id"`
	RenterID                 int64       `boil:"renter_id" json:"renter_id" toml:"renter_id" yaml:"renter_id"`
	ScheduledTime            time.Time   `boil:"scheduled_time" json:"scheduled_time" toml:"scheduled_time" yaml:"scheduled_time"`
	Status                   null.String `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	MessageFromRenter        null.String `boil:"message_from_renter" json:"message_from_renter,omitempty" toml:"message_from_renter" yaml:"message_from_renter,omitempty"`
	ResponseMessageFromOwner null.String `boil:"response_message_from_owner" json:"response_message_from_owner,omitempty" toml:"response_message_from_owner" yaml:"response_message_from_owner,omitempty"`
	RespondedAt              null.Time   `boil:"responded_at" json:"responded_at,omitempty" toml:"responded_at" yaml:"responded_at,omitempty"`
	RespondedBy              null.Int64  `boil:"responded_by" json:"responded_by,omitempty" toml:"responded_by" yaml:"responded_by,omitempty"`
	CreatedAt                null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt                null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *bookingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bookingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BookingColumns = struct {
	ID                       string
	ListingID                string
	RenterID                 string
	ScheduledTime            string
	Status                   string
	MessageFromRenter        string
	ResponseMessageFromOwner string
	RespondedAt              string
	RespondedBy              string
	CreatedAt                string
	UpdatedAt                string
}{
	ID:                       "id",
	ListingID:                "listing_id",
	RenterID:                 "renter_id",
	ScheduledTime:            "scheduled_time",
	Status:                   "status",
	MessageFromRenter:        "message_from_renter",
	ResponseMessageFromOwner: "response_message_from_owner",
	RespondedAt:              "responded_at",
	RespondedBy:              "responded_by",
	CreatedAt:                "created_at",
	UpdatedAt:                "updated_at",
}

var BookingTableColumns = struct {
	ID                       string
	ListingID                string
	RenterID                 string
	ScheduledTime            string
	Status                   string
	MessageFromRenter        string
	ResponseMessageFromOwner string
	RespondedAt              string
	RespondedBy              string
	CreatedAt                string
	UpdatedAt                string
}{
	ID:                       "bookings.id",
	ListingID:                "bookings.listing_id",
	RenterID:                 "bookings.renter_id",
	ScheduledTime:            "bookings.scheduled_time",
	Status:                   "bookings.status",
	MessageFromRenter:        "bookings.message_from_renter",
	ResponseMessageFromOwner: "bookings.response_message_from_owner",
	RespondedAt:              "bookings.responded_at",
	RespondedBy:              "bookings.responded_by",
	CreatedAt:                "bookings.created_at",
	UpdatedAt:                "bookings.updated_at",
}

// Generated where

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var BookingWhere = struct {
	ID                       whereHelperint64
	ListingID                whereHelperint64
	RenterID                 whereHelperint64
	ScheduledTime            whereHelpertime_Time
	Status                   whereHelpernull_String
	MessageFromRenter        whereHelpernull_String
	ResponseMessageFromOwner whereHelpernull_String
	RespondedAt              whereHelpernull_Time
	RespondedBy              whereHelpernull_Int64
	CreatedAt                whereHelpernull_Time
	UpdatedAt                whereHelpernull_Time
}{
	ID:                       whereHelperint64{field: "\"bookings\".\"id\""},
	ListingID:                whereHelperint64{field: "\"bookings\".\"listing_id\""},
	RenterID:                 whereHelperint64{field: "\"bookings\".\"renter_id\""},
	ScheduledTime:            whereHelpertime_Time{field: "\"bookings\".\"scheduled_time\""},
	Status:                   whereHelpernull_String{field: "\"bookings\".\"status\""},
	MessageFromRenter:        whereHelpernull_String{field: "\"bookings\".\"message_from_renter\""},
	ResponseMessageFromOwner: whereHelpernull_String{field: "\"bookings\".\"response_message_from_owner\""},
	RespondedAt:              whereHelpernull_Time{field: "\"bookings\".\"responded_at\""},
	RespondedBy:              whereHelpernull_Int64{field: "\"bookings\".\"responded_by\""},
	CreatedAt:                whereHelpernull_Time{field: "\"bookings\".\"created_at\""},
	UpdatedAt:                whereHelpernull_Time{field: "\"bookings\".\"updated_at\""},
}

// BookingRels is where relationship names are stored.
var BookingRels = struct {
	Listing         string
	Renter          string
	RespondedByUser string
}{
	Listing:         "Listing",
	Renter:          "Renter",
	RespondedByUser: "RespondedByUser",
}

// bookingR is where relationships are stored.
type bookingR struct {
	Listing         *Listing `boil:"Listing" json:"Listing" toml:"Listing" yaml:"Listing"`
	Renter          *User    `boil:"Renter" json:"Renter" toml:"Renter" yaml:"Renter"`
	RespondedByUser *User    `boil:"RespondedByUser" json:"RespondedByUser" toml:"RespondedByUser" yaml:"RespondedByUser"`
}

// NewStruct creates a new relationship struct
func (*bookingR) NewStruct() *bookingR {
	return &bookingR{}
}

func (o *Booking) GetListing() *Listing {
	if o == nil {
		return nil
	}

	return o.R.GetListing()
}

func (r *bookingR) GetListing() *Listing {
	if r == nil {
		return nil
	}

	return r.Listing
}

func (o *Booking) GetRenter() *User {
	if o == nil {
		return nil
	}

	return o.R.GetRenter()
}

func (r *bookingR) GetRenter() *User {
	if r == nil {
		return nil
	}

	return r.Renter
}

func (o *Booking) GetRespondedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetRespondedByUser()
}

func (r *bookingR) GetRespondedByUser() *User {
	if r == nil {
		return nil
	}

	return r.RespondedByUser
}

// bookingL is where Load methods for each relationship are stored.
type bookingL struct{}

var (
	bookingAllColumns            = []string{"id", "listing_id", "renter_id", "scheduled_time", "status", "message_from_renter", "response_message_from_owner", "responded_at", "responded_by", "created_at", "updated_at"}
	bookingColumnsWithoutDefault = []string{"listing_id", "renter_id", "scheduled_time"}
	bookingColumnsWithDefault    = []string{"id", "status", "message_from_renter", "response_message_from_owner", "responded_at", "responded_by", "created_at", "updated_at"}
	bookingPrimaryKeyColumns     = []string{"id"}
	bookingGeneratedColumns      = []string{"id"}
)

type (
	// BookingSlice is an alias for a slice of pointers to Booking.
	// This should almost always be used instead of []Booking.
	BookingSlice []*Booking
	// BookingHook is the signature for custom Booking hook methods
	BookingHook func(context.Context, boil.ContextExecutor, *Booking) error

	bookingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bookingType                 = reflect.TypeOf(&Booking{})
	bookingMapping              = queries.MakeStructMapping(bookingType)
	bookingPrimaryKeyMapping, _ = queries.BindMapping(bookingType, bookingMapping, bookingPrimaryKeyColumns)
	bookingInsertCacheMut       sync.RWMutex
	bookingInsertCache          = make(map[string]insertCache)
	bookingUpdateCacheMut       sync.RWMutex
	bookingUpdateCache          = make(map[string]updateCache)
	bookingUpsertCacheMut       sync.RWMutex
	bookingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bookingAfterSelectMu sync.Mutex
var bookingAfterSelectHooks []BookingHook

var bookingBeforeInsertMu sync.Mutex
var bookingBeforeInsertHooks []BookingHook
var bookingAfterInsertMu sync.Mutex
var bookingAfterInsertHooks []BookingHook

var bookingBeforeUpdateMu sync.Mutex
var bookingBeforeUpdateHooks []BookingHook
var bookingAfterUpdateMu sync.Mutex
var bookingAfterUpdateHooks []BookingHook

var bookingBeforeDeleteMu sync.Mutex
var bookingBeforeDeleteHooks []BookingHook
var bookingAfterDeleteMu sync.Mutex
var bookingAfterDeleteHooks []BookingHook

var bookingBeforeUpsertMu sync.Mutex
var bookingBeforeUpsertHooks []BookingHook
var bookingAfterUpsertMu sync.Mutex
var bookingAfterUpsertHooks []BookingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Booking) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Booking) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Booking) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Booking) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Booking) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Booking) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Booking) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Booking) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Booking) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBookingHook registers your hook function for all future operations.
func AddBookingHook(hookPoint boil.HookPoint, bookingHook BookingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bookingAfterSelectMu.Lock()
		bookingAfterSelectHooks = append(bookingAfterSelectHooks, bookingHook)
		bookingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bookingBeforeInsertMu.Lock()
		bookingBeforeInsertHooks = append(bookingBeforeInsertHooks, bookingHook)
		bookingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bookingAfterInsertMu.Lock()
		bookingAfterInsertHooks = append(bookingAfterInsertHooks, bookingHook)
		bookingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bookingBeforeUpdateMu.Lock()
		bookingBeforeUpdateHooks = append(bookingBeforeUpdateHooks, bookingHook)
		bookingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bookingAfterUpdateMu.Lock()
		bookingAfterUpdateHooks = append(bookingAfterUpdateHooks, bookingHook)
		bookingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bookingBeforeDeleteMu.Lock()
		bookingBeforeDeleteHooks = append(bookingBeforeDeleteHooks, bookingHook)
		bookingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bookingAfterDeleteMu.Lock()
		bookingAfterDeleteHooks = append(bookingAfterDeleteHooks, bookingHook)
		bookingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bookingBeforeUpsertMu.Lock()
		bookingBeforeUpsertHooks = append(bookingBeforeUpsertHooks, bookingHook)
		bookingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bookingAfterUpsertMu.Lock()
		bookingAfterUpsertHooks = append(bookingAfterUpsertHooks, bookingHook)
		bookingAfterUpsertMu.Unlock()
	}
}

// One returns a single booking record from the query.
func (q bookingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Booking, error) {
	o := &Booking{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bookings")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Booking records from the query.
func (q bookingQuery) All(ctx context.Context, exec boil.ContextExecutor) (BookingSlice, error) {
	var o []*Booking

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Booking slice")
	}

	if len(bookingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Booking records in the query.
func (q bookingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bookings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q bookingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bookings exists")
	}

	return count > 0, nil
}

// Listing pointed to by the foreign key.
func (o *Booking) Listing(mods ...qm.QueryMod) listingQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ListingID),
	}

	queryMods = append(queryMods, mods...)

	return Listings(queryMods...)
}

// Renter pointed to by the foreign key.
func (o *Booking) Renter(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RenterID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// RespondedByUser pointed to by the foreign key.
func (o *Booking) RespondedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RespondedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadListing allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookingL) LoadListing(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBooking interface{}, mods queries.Applicator) error {
	var slice []*Booking
	var object *Booking

	if singular {
		var ok bool
		object, ok = maybeBooking.(*Booking)
		if !ok {
			object = new(Booking)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBooking))
			}
		}
	} else {
		s, ok := maybeBooking.(*[]*Booking)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBooking))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingR{}
		}
		args[object.ListingID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingR{}
			}

			args[obj.ListingID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`listings`),
		qm.WhereIn(`listings.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Listing")
	}

	var resultSlice []*Listing
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Listing")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for listings")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for listings")
	}

	if len(listingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Listing = foreign
		if foreign.R == nil {
			foreign.R = &listingR{}
		}
		foreign.R.Bookings = append(foreign.R.Bookings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ListingID == foreign.ID {
				local.R.Listing = foreign
				if foreign.R == nil {
					foreign.R = &listingR{}
				}
				foreign.R.Bookings = append(foreign.R.Bookings, local)
				break
			}
		}
	}

	return nil
}

// LoadRenter allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookingL) LoadRenter(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBooking interface{}, mods queries.Applicator) error {
	var slice []*Booking
	var object *Booking

	if singular {
		var ok bool
		object, ok = maybeBooking.(*Booking)
		if !ok {
			object = new(Booking)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBooking))
			}
		}
	} else {
		s, ok := maybeBooking.(*[]*Booking)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBooking))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingR{}
		}
		args[object.RenterID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingR{}
			}

			args[obj.RenterID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Renter = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.RenterBookings = append(foreign.R.RenterBookings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RenterID == foreign.ID {
				local.R.Renter = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.RenterBookings = append(foreign.R.RenterBookings, local)
				break
			}
		}
	}

	return nil
}

// LoadRespondedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookingL) LoadRespondedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBooking interface{}, mods queries.Applicator) error {
	var slice []*Booking
	var object *Booking

	if singular {
		var ok bool
		object, ok = maybeBooking.(*Booking)
		if !ok {
			object = new(Booking)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBooking))
			}
		}
	} else {
		s, ok := maybeBooking.(*[]*Booking)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBooking)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBooking))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingR{}
		}
		if !queries.IsNil(object.RespondedBy) {
			args[object.RespondedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingR{}
			}

			if !queries.IsNil(obj.RespondedBy) {
				args[obj.RespondedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RespondedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.RespondedByBookings = append(foreign.R.RespondedByBookings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.RespondedBy, foreign.ID) {
				local.R.RespondedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.RespondedByBookings = append(foreign.R.RespondedByBookings, local)
				break
			}
		}
	}

	return nil
}

// SetListing of the booking to the related item.
// Sets o.R.Listing to related.
// Adds o to related.R.Bookings.
func (o *Booking) SetListing(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Listing) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bookings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"listing_id"}),
		strmangle.WhereClause("\"", "\"", 2, bookingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ListingID = related.ID
	if o.R == nil {
		o.R = &bookingR{
			Listing: related,
		}
	} else {
		o.R.Listing = related
	}

	if related.R == nil {
		related.R = &listingR{
			Bookings: BookingSlice{o},
		}
	} else {
		related.R.Bookings = append(related.R.Bookings, o)
	}

	return nil
}

// SetRenter of the booking to the related item.
// Sets o.R.Renter to related.
// Adds o to related.R.RenterBookings.
func (o *Booking) SetRenter(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bookings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"renter_id"}),
		strmangle.WhereClause("\"", "\"", 2, bookingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RenterID = related.ID
	if o.R == nil {
		o.R = &bookingR{
			Renter: related,
		}
	} else {
		o.R.Renter = related
	}

	if related.R == nil {
		related.R = &userR{
			RenterBookings: BookingSlice{o},
		}
	} else {
		related.R.RenterBookings = append(related.R.RenterBookings, o)
	}

	return nil
}

// SetRespondedByUser of the booking to the related item.
// Sets o.R.RespondedByUser to related.
// Adds o to related.R.RespondedByBookings.
func (o *Booking) SetRespondedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bookings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"responded_by"}),
		strmangle.WhereClause("\"", "\"", 2, bookingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.RespondedBy, related.ID)
	if o.R == nil {
		o.R = &bookingR{
			RespondedByUser: related,
		}
	} else {
		o.R.RespondedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			RespondedByBookings: BookingSlice{o},
		}
	} else {
		related.R.RespondedByBookings = append(related.R.RespondedByBookings, o)
	}

	return nil
}

// RemoveRespondedByUser relationship.
// Sets o.R.RespondedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Booking) RemoveRespondedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.RespondedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("responded_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.RespondedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.RespondedByBookings {
		if queries.Equal(o.RespondedBy, ri.RespondedBy) {
			continue
		}

		ln := len(related.R.RespondedByBookings)
		if ln > 1 && i < ln-1 {
			related.R.RespondedByBookings[i] = related.R.RespondedByBookings[ln-1]
		}
		related.R.RespondedByBookings = related.R.RespondedByBookings[:ln-1]
		break
	}
	return nil
}

// Bookings retrieves all the records using an executor.
func Bookings(mods ...qm.QueryMod) bookingQuery {
	mods = append(mods, qm.From("\"bookings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"bookings\".*"})
	}

	return bookingQuery{q}
}

// FindBooking retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBooking(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Booking, error) {
	bookingObj := &Booking{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"bookings\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, bookingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bookings")
	}

	if err = bookingObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bookingObj, err
	}

	return bookingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Booking) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bookings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bookingInsertCacheMut.RLock()
	cache, cached := bookingInsertCache[key]
	bookingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bookingAllColumns,
			bookingColumnsWithDefault,
			bookingColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, bookingGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(bookingType, bookingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bookingType, bookingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"bookings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"bookings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bookings")
	}

	if !cached {
		bookingInsertCacheMut.Lock()
		bookingInsertCache[key] = cache
		bookingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Booking.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Booking) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bookingUpdateCacheMut.RLock()
	cache, cached := bookingUpdateCache[key]
	bookingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bookingAllColumns,
			bookingPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, bookingGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bookings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"bookings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bookingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bookingType, bookingMapping, append(wl, bookingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bookings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bookings")
	}

	if !cached {
		bookingUpdateCacheMut.Lock()
		bookingUpdateCache[key] = cache
		bookingUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q bookingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bookings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bookings")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BookingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"bookings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bookingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in booking slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all booking")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Booking) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no bookings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bookingUpsertCacheMut.RLock()
	cache, cached := bookingUpsertCache[key]
	bookingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bookingAllColumns,
			bookingColumnsWithDefault,
			bookingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			bookingAllColumns,
			bookingPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, bookingGeneratedColumns)
		update = strmangle.SetComplement(update, bookingGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert bookings, could not build update column list")
		}

		ret := strmangle.SetComplement(bookingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(bookingPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert bookings, could not build conflict column list")
			}

			conflict = make([]string, len(bookingPrimaryKeyColumns))
			copy(conflict, bookingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"bookings\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(bookingType, bookingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bookingType, bookingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert bookings")
	}

	if !cached {
		bookingUpsertCacheMut.Lock()
		bookingUpsertCache[key] = cache
		bookingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Booking record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Booking) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Booking provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bookingPrimaryKeyMapping)
	sql := "DELETE FROM \"bookings\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bookings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bookings")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q bookingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no bookingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bookings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bookings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BookingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bookingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"bookings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from booking slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bookings")
	}

	if len(bookingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Booking) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBooking(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BookingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BookingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"bookings\".* FROM \"bookings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BookingSlice")
	}

	*o = slice

	return nil
}

// BookingExists checks if the Booking row exists.
func BookingExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"bookings\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bookings exists")
	}

	return exists, nil
}

// Exists checks if the Booking row exists.
func (o *Booking) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BookingExists(ctx, exec, o.ID)
}
