// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EmailTemplate is an object representing the database table.
type EmailTemplate struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Subject   string    `boil:"subject" json:"subject" toml:"subject" yaml:"subject"`
	Body      string    `boil:"body" json:"body" toml:"body" yaml:"body"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *emailTemplateR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailTemplateL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailTemplateColumns = struct {
	ID        string
	Name      string
	Subject   string
	Body      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	Subject:   "subject",
	Body:      "body",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var EmailTemplateTableColumns = struct {
	ID        string
	Name      string
	Subject   string
	Body      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "email_templates.id",
	Name:      "email_templates.name",
	Subject:   "email_templates.subject",
	Body:      "email_templates.body",
	CreatedAt: "email_templates.created_at",
	UpdatedAt: "email_templates.updated_at",
}

// Generated where

var EmailTemplateWhere = struct {
	ID        whereHelperint
	Name      whereHelperstring
	Subject   whereHelperstring
	Body      whereHelperstring
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperint{field: "\"email_templates\".\"id\""},
	Name:      whereHelperstring{field: "\"email_templates\".\"name\""},
	Subject:   whereHelperstring{field: "\"email_templates\".\"subject\""},
	Body:      whereHelperstring{field: "\"email_templates\".\"body\""},
	CreatedAt: whereHelpernull_Time{field: "\"email_templates\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"email_templates\".\"updated_at\""},
}

// EmailTemplateRels is where relationship names are stored.
var EmailTemplateRels = struct {
}{}

// emailTemplateR is where relationships are stored.
type emailTemplateR struct {
}

// NewStruct creates a new relationship struct
func (*emailTemplateR) NewStruct() *emailTemplateR {
	return &emailTemplateR{}
}

// emailTemplateL is where Load methods for each relationship are stored.
type emailTemplateL struct{}

var (
	emailTemplateAllColumns            = []string{"id", "name", "subject", "body", "created_at", "updated_at"}
	emailTemplateColumnsWithoutDefault = []string{"name", "subject", "body"}
	emailTemplateColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	emailTemplatePrimaryKeyColumns     = []string{"id"}
	emailTemplateGeneratedColumns      = []string{}
)

type (
	// EmailTemplateSlice is an alias for a slice of pointers to EmailTemplate.
	// This should almost always be used instead of []EmailTemplate.
	EmailTemplateSlice []*EmailTemplate
	// EmailTemplateHook is the signature for custom EmailTemplate hook methods
	EmailTemplateHook func(context.Context, boil.ContextExecutor, *EmailTemplate) error

	emailTemplateQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailTemplateType                 = reflect.TypeOf(&EmailTemplate{})
	emailTemplateMapping              = queries.MakeStructMapping(emailTemplateType)
	emailTemplatePrimaryKeyMapping, _ = queries.BindMapping(emailTemplateType, emailTemplateMapping, emailTemplatePrimaryKeyColumns)
	emailTemplateInsertCacheMut       sync.RWMutex
	emailTemplateInsertCache          = make(map[string]insertCache)
	emailTemplateUpdateCacheMut       sync.RWMutex
	emailTemplateUpdateCache          = make(map[string]updateCache)
	emailTemplateUpsertCacheMut       sync.RWMutex
	emailTemplateUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailTemplateAfterSelectMu sync.Mutex
var emailTemplateAfterSelectHooks []EmailTemplateHook

var emailTemplateBeforeInsertMu sync.Mutex
var emailTemplateBeforeInsertHooks []EmailTemplateHook
var emailTemplateAfterInsertMu sync.Mutex
var emailTemplateAfterInsertHooks []EmailTemplateHook

var emailTemplateBeforeUpdateMu sync.Mutex
var emailTemplateBeforeUpdateHooks []EmailTemplateHook
var emailTemplateAfterUpdateMu sync.Mutex
var emailTemplateAfterUpdateHooks []EmailTemplateHook

var emailTemplateBeforeDeleteMu sync.Mutex
var emailTemplateBeforeDeleteHooks []EmailTemplateHook
var emailTemplateAfterDeleteMu sync.Mutex
var emailTemplateAfterDeleteHooks []EmailTemplateHook

var emailTemplateBeforeUpsertMu sync.Mutex
var emailTemplateBeforeUpsertHooks []EmailTemplateHook
var emailTemplateAfterUpsertMu sync.Mutex
var emailTemplateAfterUpsertHooks []EmailTemplateHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailTemplate) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailTemplate) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailTemplate) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailTemplate) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailTemplate) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailTemplate) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailTemplate) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailTemplate) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailTemplate) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailTemplateAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailTemplateHook registers your hook function for all future operations.
func AddEmailTemplateHook(hookPoint boil.HookPoint, emailTemplateHook EmailTemplateHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailTemplateAfterSelectMu.Lock()
		emailTemplateAfterSelectHooks = append(emailTemplateAfterSelectHooks, emailTemplateHook)
		emailTemplateAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailTemplateBeforeInsertMu.Lock()
		emailTemplateBeforeInsertHooks = append(emailTemplateBeforeInsertHooks, emailTemplateHook)
		emailTemplateBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailTemplateAfterInsertMu.Lock()
		emailTemplateAfterInsertHooks = append(emailTemplateAfterInsertHooks, emailTemplateHook)
		emailTemplateAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailTemplateBeforeUpdateMu.Lock()
		emailTemplateBeforeUpdateHooks = append(emailTemplateBeforeUpdateHooks, emailTemplateHook)
		emailTemplateBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailTemplateAfterUpdateMu.Lock()
		emailTemplateAfterUpdateHooks = append(emailTemplateAfterUpdateHooks, emailTemplateHook)
		emailTemplateAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailTemplateBeforeDeleteMu.Lock()
		emailTemplateBeforeDeleteHooks = append(emailTemplateBeforeDeleteHooks, emailTemplateHook)
		emailTemplateBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailTemplateAfterDeleteMu.Lock()
		emailTemplateAfterDeleteHooks = append(emailTemplateAfterDeleteHooks, emailTemplateHook)
		emailTemplateAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailTemplateBeforeUpsertMu.Lock()
		emailTemplateBeforeUpsertHooks = append(emailTemplateBeforeUpsertHooks, emailTemplateHook)
		emailTemplateBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailTemplateAfterUpsertMu.Lock()
		emailTemplateAfterUpsertHooks = append(emailTemplateAfterUpsertHooks, emailTemplateHook)
		emailTemplateAfterUpsertMu.Unlock()
	}
}

// One returns a single emailTemplate record from the query.
func (q emailTemplateQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailTemplate, error) {
	o := &EmailTemplate{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for email_templates")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailTemplate records from the query.
func (q emailTemplateQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailTemplateSlice, error) {
	var o []*EmailTemplate

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EmailTemplate slice")
	}

	if len(emailTemplateAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailTemplate records in the query.
func (q emailTemplateQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count email_templates rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailTemplateQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if email_templates exists")
	}

	return count > 0, nil
}

// EmailTemplates retrieves all the records using an executor.
func EmailTemplates(mods ...qm.QueryMod) emailTemplateQuery {
	mods = append(mods, qm.From("\"email_templates\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"email_templates\".*"})
	}

	return emailTemplateQuery{q}
}

// FindEmailTemplate retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailTemplate(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*EmailTemplate, error) {
	emailTemplateObj := &EmailTemplate{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"email_templates\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, emailTemplateObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from email_templates")
	}

	if err = emailTemplateObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailTemplateObj, err
	}

	return emailTemplateObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailTemplate) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no email_templates provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailTemplateColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailTemplateInsertCacheMut.RLock()
	cache, cached := emailTemplateInsertCache[key]
	emailTemplateInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailTemplateAllColumns,
			emailTemplateColumnsWithDefault,
			emailTemplateColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailTemplateType, emailTemplateMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailTemplateType, emailTemplateMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"email_templates\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"email_templates\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into email_templates")
	}

	if !cached {
		emailTemplateInsertCacheMut.Lock()
		emailTemplateInsertCache[key] = cache
		emailTemplateInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailTemplate.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailTemplate) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailTemplateUpdateCacheMut.RLock()
	cache, cached := emailTemplateUpdateCache[key]
	emailTemplateUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailTemplateAllColumns,
			emailTemplatePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update email_templates, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"email_templates\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailTemplatePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailTemplateType, emailTemplateMapping, append(wl, emailTemplatePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update email_templates row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for email_templates")
	}

	if !cached {
		emailTemplateUpdateCacheMut.Lock()
		emailTemplateUpdateCache[key] = cache
		emailTemplateUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailTemplateQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for email_templates")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for email_templates")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailTemplateSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailTemplatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"email_templates\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailTemplatePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in emailTemplate slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all emailTemplate")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailTemplate) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no email_templates provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailTemplateColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailTemplateUpsertCacheMut.RLock()
	cache, cached := emailTemplateUpsertCache[key]
	emailTemplateUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailTemplateAllColumns,
			emailTemplateColumnsWithDefault,
			emailTemplateColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailTemplateAllColumns,
			emailTemplatePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert email_templates, could not build update column list")
		}

		ret := strmangle.SetComplement(emailTemplateAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailTemplatePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert email_templates, could not build conflict column list")
			}

			conflict = make([]string, len(emailTemplatePrimaryKeyColumns))
			copy(conflict, emailTemplatePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"email_templates\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailTemplateType, emailTemplateMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailTemplateType, emailTemplateMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert email_templates")
	}

	if !cached {
		emailTemplateUpsertCacheMut.Lock()
		emailTemplateUpsertCache[key] = cache
		emailTemplateUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailTemplate record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailTemplate) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EmailTemplate provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailTemplatePrimaryKeyMapping)
	sql := "DELETE FROM \"email_templates\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from email_templates")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for email_templates")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailTemplateQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no emailTemplateQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from email_templates")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_templates")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailTemplateSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailTemplateBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailTemplatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"email_templates\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailTemplatePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from emailTemplate slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_templates")
	}

	if len(emailTemplateAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailTemplate) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailTemplate(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailTemplateSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailTemplateSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailTemplatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"email_templates\".* FROM \"email_templates\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailTemplatePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EmailTemplateSlice")
	}

	*o = slice

	return nil
}

// EmailTemplateExists checks if the EmailTemplate row exists.
func EmailTemplateExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"email_templates\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if email_templates exists")
	}

	return exists, nil
}

// Exists checks if the EmailTemplate row exists.
func (o *EmailTemplate) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailTemplateExists(ctx, exec, o.ID)
}
