// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ListingImage is an object representing the database table.
type ListingImage struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	ListingID int64     `boil:"listing_id" json:"listing_id" toml:"listing_id" yaml:"listing_id"`
	ImageURL  string    `boil:"image_url" json:"image_url" toml:"image_url" yaml:"image_url"`
	IsMain    null.Bool `boil:"is_main" json:"is_main,omitempty" toml:"is_main" yaml:"is_main,omitempty"`
	SortOrder null.Int  `boil:"sort_order" json:"sort_order,omitempty" toml:"sort_order" yaml:"sort_order,omitempty"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *listingImageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L listingImageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ListingImageColumns = struct {
	ID        string
	ListingID string
	ImageURL  string
	IsMain    string
	SortOrder string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	ListingID: "listing_id",
	ImageURL:  "image_url",
	IsMain:    "is_main",
	SortOrder: "sort_order",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var ListingImageTableColumns = struct {
	ID        string
	ListingID string
	ImageURL  string
	IsMain    string
	SortOrder string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "listing_images.id",
	ListingID: "listing_images.listing_id",
	ImageURL:  "listing_images.image_url",
	IsMain:    "listing_images.is_main",
	SortOrder: "listing_images.sort_order",
	CreatedAt: "listing_images.created_at",
	UpdatedAt: "listing_images.updated_at",
}

// Generated where

var ListingImageWhere = struct {
	ID        whereHelperint64
	ListingID whereHelperint64
	ImageURL  whereHelperstring
	IsMain    whereHelpernull_Bool
	SortOrder whereHelpernull_Int
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperint64{field: "\"listing_images\".\"id\""},
	ListingID: whereHelperint64{field: "\"listing_images\".\"listing_id\""},
	ImageURL:  whereHelperstring{field: "\"listing_images\".\"image_url\""},
	IsMain:    whereHelpernull_Bool{field: "\"listing_images\".\"is_main\""},
	SortOrder: whereHelpernull_Int{field: "\"listing_images\".\"sort_order\""},
	CreatedAt: whereHelpernull_Time{field: "\"listing_images\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"listing_images\".\"updated_at\""},
}

// ListingImageRels is where relationship names are stored.
var ListingImageRels = struct {
	Listing string
}{
	Listing: "Listing",
}

// listingImageR is where relationships are stored.
type listingImageR struct {
	Listing *Listing `boil:"Listing" json:"Listing" toml:"Listing" yaml:"Listing"`
}

// NewStruct creates a new relationship struct
func (*listingImageR) NewStruct() *listingImageR {
	return &listingImageR{}
}

func (o *ListingImage) GetListing() *Listing {
	if o == nil {
		return nil
	}

	return o.R.GetListing()
}

func (r *listingImageR) GetListing() *Listing {
	if r == nil {
		return nil
	}

	return r.Listing
}

// listingImageL is where Load methods for each relationship are stored.
type listingImageL struct{}

var (
	listingImageAllColumns            = []string{"id", "listing_id", "image_url", "is_main", "sort_order", "created_at", "updated_at"}
	listingImageColumnsWithoutDefault = []string{"listing_id", "image_url"}
	listingImageColumnsWithDefault    = []string{"id", "is_main", "sort_order", "created_at", "updated_at"}
	listingImagePrimaryKeyColumns     = []string{"id"}
	listingImageGeneratedColumns      = []string{"id"}
)

type (
	// ListingImageSlice is an alias for a slice of pointers to ListingImage.
	// This should almost always be used instead of []ListingImage.
	ListingImageSlice []*ListingImage
	// ListingImageHook is the signature for custom ListingImage hook methods
	ListingImageHook func(context.Context, boil.ContextExecutor, *ListingImage) error

	listingImageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	listingImageType                 = reflect.TypeOf(&ListingImage{})
	listingImageMapping              = queries.MakeStructMapping(listingImageType)
	listingImagePrimaryKeyMapping, _ = queries.BindMapping(listingImageType, listingImageMapping, listingImagePrimaryKeyColumns)
	listingImageInsertCacheMut       sync.RWMutex
	listingImageInsertCache          = make(map[string]insertCache)
	listingImageUpdateCacheMut       sync.RWMutex
	listingImageUpdateCache          = make(map[string]updateCache)
	listingImageUpsertCacheMut       sync.RWMutex
	listingImageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var listingImageAfterSelectMu sync.Mutex
var listingImageAfterSelectHooks []ListingImageHook

var listingImageBeforeInsertMu sync.Mutex
var listingImageBeforeInsertHooks []ListingImageHook
var listingImageAfterInsertMu sync.Mutex
var listingImageAfterInsertHooks []ListingImageHook

var listingImageBeforeUpdateMu sync.Mutex
var listingImageBeforeUpdateHooks []ListingImageHook
var listingImageAfterUpdateMu sync.Mutex
var listingImageAfterUpdateHooks []ListingImageHook

var listingImageBeforeDeleteMu sync.Mutex
var listingImageBeforeDeleteHooks []ListingImageHook
var listingImageAfterDeleteMu sync.Mutex
var listingImageAfterDeleteHooks []ListingImageHook

var listingImageBeforeUpsertMu sync.Mutex
var listingImageBeforeUpsertHooks []ListingImageHook
var listingImageAfterUpsertMu sync.Mutex
var listingImageAfterUpsertHooks []ListingImageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ListingImage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ListingImage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ListingImage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ListingImage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ListingImage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ListingImage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ListingImage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ListingImage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ListingImage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listingImageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddListingImageHook registers your hook function for all future operations.
func AddListingImageHook(hookPoint boil.HookPoint, listingImageHook ListingImageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		listingImageAfterSelectMu.Lock()
		listingImageAfterSelectHooks = append(listingImageAfterSelectHooks, listingImageHook)
		listingImageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		listingImageBeforeInsertMu.Lock()
		listingImageBeforeInsertHooks = append(listingImageBeforeInsertHooks, listingImageHook)
		listingImageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		listingImageAfterInsertMu.Lock()
		listingImageAfterInsertHooks = append(listingImageAfterInsertHooks, listingImageHook)
		listingImageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		listingImageBeforeUpdateMu.Lock()
		listingImageBeforeUpdateHooks = append(listingImageBeforeUpdateHooks, listingImageHook)
		listingImageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		listingImageAfterUpdateMu.Lock()
		listingImageAfterUpdateHooks = append(listingImageAfterUpdateHooks, listingImageHook)
		listingImageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		listingImageBeforeDeleteMu.Lock()
		listingImageBeforeDeleteHooks = append(listingImageBeforeDeleteHooks, listingImageHook)
		listingImageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		listingImageAfterDeleteMu.Lock()
		listingImageAfterDeleteHooks = append(listingImageAfterDeleteHooks, listingImageHook)
		listingImageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		listingImageBeforeUpsertMu.Lock()
		listingImageBeforeUpsertHooks = append(listingImageBeforeUpsertHooks, listingImageHook)
		listingImageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		listingImageAfterUpsertMu.Lock()
		listingImageAfterUpsertHooks = append(listingImageAfterUpsertHooks, listingImageHook)
		listingImageAfterUpsertMu.Unlock()
	}
}

// One returns a single listingImage record from the query.
func (q listingImageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ListingImage, error) {
	o := &ListingImage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for listing_images")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ListingImage records from the query.
func (q listingImageQuery) All(ctx context.Context, exec boil.ContextExecutor) (ListingImageSlice, error) {
	var o []*ListingImage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ListingImage slice")
	}

	if len(listingImageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ListingImage records in the query.
func (q listingImageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count listing_images rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q listingImageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if listing_images exists")
	}

	return count > 0, nil
}

// Listing pointed to by the foreign key.
func (o *ListingImage) Listing(mods ...qm.QueryMod) listingQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ListingID),
	}

	queryMods = append(queryMods, mods...)

	return Listings(queryMods...)
}

// LoadListing allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (listingImageL) LoadListing(ctx context.Context, e boil.ContextExecutor, singular bool, maybeListingImage interface{}, mods queries.Applicator) error {
	var slice []*ListingImage
	var object *ListingImage

	if singular {
		var ok bool
		object, ok = maybeListingImage.(*ListingImage)
		if !ok {
			object = new(ListingImage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeListingImage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeListingImage))
			}
		}
	} else {
		s, ok := maybeListingImage.(*[]*ListingImage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeListingImage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeListingImage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &listingImageR{}
		}
		args[object.ListingID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &listingImageR{}
			}

			args[obj.ListingID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`listings`),
		qm.WhereIn(`listings.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Listing")
	}

	var resultSlice []*Listing
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Listing")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for listings")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for listings")
	}

	if len(listingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Listing = foreign
		if foreign.R == nil {
			foreign.R = &listingR{}
		}
		foreign.R.ListingImages = append(foreign.R.ListingImages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ListingID == foreign.ID {
				local.R.Listing = foreign
				if foreign.R == nil {
					foreign.R = &listingR{}
				}
				foreign.R.ListingImages = append(foreign.R.ListingImages, local)
				break
			}
		}
	}

	return nil
}

// SetListing of the listingImage to the related item.
// Sets o.R.Listing to related.
// Adds o to related.R.ListingImages.
func (o *ListingImage) SetListing(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Listing) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"listing_images\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"listing_id"}),
		strmangle.WhereClause("\"", "\"", 2, listingImagePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ListingID = related.ID
	if o.R == nil {
		o.R = &listingImageR{
			Listing: related,
		}
	} else {
		o.R.Listing = related
	}

	if related.R == nil {
		related.R = &listingR{
			ListingImages: ListingImageSlice{o},
		}
	} else {
		related.R.ListingImages = append(related.R.ListingImages, o)
	}

	return nil
}

// ListingImages retrieves all the records using an executor.
func ListingImages(mods ...qm.QueryMod) listingImageQuery {
	mods = append(mods, qm.From("\"listing_images\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"listing_images\".*"})
	}

	return listingImageQuery{q}
}

// FindListingImage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindListingImage(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ListingImage, error) {
	listingImageObj := &ListingImage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"listing_images\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, listingImageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from listing_images")
	}

	if err = listingImageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return listingImageObj, err
	}

	return listingImageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ListingImage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no listing_images provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(listingImageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	listingImageInsertCacheMut.RLock()
	cache, cached := listingImageInsertCache[key]
	listingImageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			listingImageAllColumns,
			listingImageColumnsWithDefault,
			listingImageColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, listingImageGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(listingImageType, listingImageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(listingImageType, listingImageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"listing_images\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"listing_images\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into listing_images")
	}

	if !cached {
		listingImageInsertCacheMut.Lock()
		listingImageInsertCache[key] = cache
		listingImageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ListingImage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ListingImage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	listingImageUpdateCacheMut.RLock()
	cache, cached := listingImageUpdateCache[key]
	listingImageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			listingImageAllColumns,
			listingImagePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, listingImageGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update listing_images, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"listing_images\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, listingImagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(listingImageType, listingImageMapping, append(wl, listingImagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update listing_images row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for listing_images")
	}

	if !cached {
		listingImageUpdateCacheMut.Lock()
		listingImageUpdateCache[key] = cache
		listingImageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q listingImageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for listing_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for listing_images")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ListingImageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listingImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"listing_images\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, listingImagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in listingImage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all listingImage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ListingImage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no listing_images provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(listingImageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	listingImageUpsertCacheMut.RLock()
	cache, cached := listingImageUpsertCache[key]
	listingImageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			listingImageAllColumns,
			listingImageColumnsWithDefault,
			listingImageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			listingImageAllColumns,
			listingImagePrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, listingImageGeneratedColumns)
		update = strmangle.SetComplement(update, listingImageGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert listing_images, could not build update column list")
		}

		ret := strmangle.SetComplement(listingImageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(listingImagePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert listing_images, could not build conflict column list")
			}

			conflict = make([]string, len(listingImagePrimaryKeyColumns))
			copy(conflict, listingImagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"listing_images\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(listingImageType, listingImageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(listingImageType, listingImageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert listing_images")
	}

	if !cached {
		listingImageUpsertCacheMut.Lock()
		listingImageUpsertCache[key] = cache
		listingImageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ListingImage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ListingImage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ListingImage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), listingImagePrimaryKeyMapping)
	sql := "DELETE FROM \"listing_images\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from listing_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for listing_images")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q listingImageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no listingImageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from listing_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for listing_images")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ListingImageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(listingImageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listingImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"listing_images\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, listingImagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from listingImage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for listing_images")
	}

	if len(listingImageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ListingImage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindListingImage(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ListingImageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ListingImageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listingImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"listing_images\".* FROM \"listing_images\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, listingImagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ListingImageSlice")
	}

	*o = slice

	return nil
}

// ListingImageExists checks if the ListingImage row exists.
func ListingImageExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"listing_images\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if listing_images exists")
	}

	return exists, nil
}

// Exists checks if the ListingImage row exists.
func (o *ListingImage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ListingImageExists(ctx, exec, o.ID)
}
