// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SearchLog is an object representing the database table.
type SearchLog struct {
	ID                int64             `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID            null.Int64        `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	Keyword           null.String       `boil:"keyword" json:"keyword,omitempty" toml:"keyword" yaml:"keyword,omitempty"`
	LocationID        null.Int64        `boil:"location_id" json:"location_id,omitempty" toml:"location_id" yaml:"location_id,omitempty"`
	MinPrice          types.NullDecimal `boil:"min_price" json:"min_price,omitempty" toml:"min_price" yaml:"min_price,omitempty"`
	MaxPrice          types.NullDecimal `boil:"max_price" json:"max_price,omitempty" toml:"max_price" yaml:"max_price,omitempty"`
	MinAreaM2         types.NullDecimal `boil:"min_area_m2" json:"min_area_m2,omitempty" toml:"min_area_m2" yaml:"min_area_m2,omitempty"`
	MaxAreaM2         types.NullDecimal `boil:"max_area_m2" json:"max_area_m2,omitempty" toml:"max_area_m2" yaml:"max_area_m2,omitempty"`
	NumBedrooms       null.Int          `boil:"num_bedrooms" json:"num_bedrooms,omitempty" toml:"num_bedrooms" yaml:"num_bedrooms,omitempty"`
	NumBathrooms      null.Int          `boil:"num_bathrooms" json:"num_bathrooms,omitempty" toml:"num_bathrooms" yaml:"num_bathrooms,omitempty"`
	NumFloors         null.Int          `boil:"num_floors" json:"num_floors,omitempty" toml:"num_floors" yaml:"num_floors,omitempty"`
	PropertyType      null.String       `boil:"property_type" json:"property_type,omitempty" toml:"property_type" yaml:"property_type,omitempty"`
	PetAllowed        null.Bool         `boil:"pet_allowed" json:"pet_allowed,omitempty" toml:"pet_allowed" yaml:"pet_allowed,omitempty"`
	HasBalcony        null.Bool         `boil:"has_balcony" json:"has_balcony,omitempty" toml:"has_balcony" yaml:"has_balcony,omitempty"`
	HasParking        null.Bool         `boil:"has_parking" json:"has_parking,omitempty" toml:"has_parking" yaml:"has_parking,omitempty"`
	AdditionalFilters null.JSON         `boil:"additional_filters" json:"additional_filters,omitempty" toml:"additional_filters" yaml:"additional_filters,omitempty"`
	SearchCount       null.Int          `boil:"search_count" json:"search_count,omitempty" toml:"search_count" yaml:"search_count,omitempty"`
	CreatedAt         null.Time         `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt         null.Time         `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *searchLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L searchLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SearchLogColumns = struct {
	ID                string
	UserID            string
	Keyword           string
	LocationID        string
	MinPrice          string
	MaxPrice          string
	MinAreaM2         string
	MaxAreaM2         string
	NumBedrooms       string
	NumBathrooms      string
	NumFloors         string
	PropertyType      string
	PetAllowed        string
	HasBalcony        string
	HasParking        string
	AdditionalFilters string
	SearchCount       string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	UserID:            "user_id",
	Keyword:           "keyword",
	LocationID:        "location_id",
	MinPrice:          "min_price",
	MaxPrice:          "max_price",
	MinAreaM2:         "min_area_m2",
	MaxAreaM2:         "max_area_m2",
	NumBedrooms:       "num_bedrooms",
	NumBathrooms:      "num_bathrooms",
	NumFloors:         "num_floors",
	PropertyType:      "property_type",
	PetAllowed:        "pet_allowed",
	HasBalcony:        "has_balcony",
	HasParking:        "has_parking",
	AdditionalFilters: "additional_filters",
	SearchCount:       "search_count",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var SearchLogTableColumns = struct {
	ID                string
	UserID            string
	Keyword           string
	LocationID        string
	MinPrice          string
	MaxPrice          string
	MinAreaM2         string
	MaxAreaM2         string
	NumBedrooms       string
	NumBathrooms      string
	NumFloors         string
	PropertyType      string
	PetAllowed        string
	HasBalcony        string
	HasParking        string
	AdditionalFilters string
	SearchCount       string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "search_logs.id",
	UserID:            "search_logs.user_id",
	Keyword:           "search_logs.keyword",
	LocationID:        "search_logs.location_id",
	MinPrice:          "search_logs.min_price",
	MaxPrice:          "search_logs.max_price",
	MinAreaM2:         "search_logs.min_area_m2",
	MaxAreaM2:         "search_logs.max_area_m2",
	NumBedrooms:       "search_logs.num_bedrooms",
	NumBathrooms:      "search_logs.num_bathrooms",
	NumFloors:         "search_logs.num_floors",
	PropertyType:      "search_logs.property_type",
	PetAllowed:        "search_logs.pet_allowed",
	HasBalcony:        "search_logs.has_balcony",
	HasParking:        "search_logs.has_parking",
	AdditionalFilters: "search_logs.additional_filters",
	SearchCount:       "search_logs.search_count",
	CreatedAt:         "search_logs.created_at",
	UpdatedAt:         "search_logs.updated_at",
}

// Generated where

var SearchLogWhere = struct {
	ID                whereHelperint64
	UserID            whereHelpernull_Int64
	Keyword           whereHelpernull_String
	LocationID        whereHelpernull_Int64
	MinPrice          whereHelpertypes_NullDecimal
	MaxPrice          whereHelpertypes_NullDecimal
	MinAreaM2         whereHelpertypes_NullDecimal
	MaxAreaM2         whereHelpertypes_NullDecimal
	NumBedrooms       whereHelpernull_Int
	NumBathrooms      whereHelpernull_Int
	NumFloors         whereHelpernull_Int
	PropertyType      whereHelpernull_String
	PetAllowed        whereHelpernull_Bool
	HasBalcony        whereHelpernull_Bool
	HasParking        whereHelpernull_Bool
	AdditionalFilters whereHelpernull_JSON
	SearchCount       whereHelpernull_Int
	CreatedAt         whereHelpernull_Time
	UpdatedAt         whereHelpernull_Time
}{
	ID:                whereHelperint64{field: "\"search_logs\".\"id\""},
	UserID:            whereHelpernull_Int64{field: "\"search_logs\".\"user_id\""},
	Keyword:           whereHelpernull_String{field: "\"search_logs\".\"keyword\""},
	LocationID:        whereHelpernull_Int64{field: "\"search_logs\".\"location_id\""},
	MinPrice:          whereHelpertypes_NullDecimal{field: "\"search_logs\".\"min_price\""},
	MaxPrice:          whereHelpertypes_NullDecimal{field: "\"search_logs\".\"max_price\""},
	MinAreaM2:         whereHelpertypes_NullDecimal{field: "\"search_logs\".\"min_area_m2\""},
	MaxAreaM2:         whereHelpertypes_NullDecimal{field: "\"search_logs\".\"max_area_m2\""},
	NumBedrooms:       whereHelpernull_Int{field: "\"search_logs\".\"num_bedrooms\""},
	NumBathrooms:      whereHelpernull_Int{field: "\"search_logs\".\"num_bathrooms\""},
	NumFloors:         whereHelpernull_Int{field: "\"search_logs\".\"num_floors\""},
	PropertyType:      whereHelpernull_String{field: "\"search_logs\".\"property_type\""},
	PetAllowed:        whereHelpernull_Bool{field: "\"search_logs\".\"pet_allowed\""},
	HasBalcony:        whereHelpernull_Bool{field: "\"search_logs\".\"has_balcony\""},
	HasParking:        whereHelpernull_Bool{field: "\"search_logs\".\"has_parking\""},
	AdditionalFilters: whereHelpernull_JSON{field: "\"search_logs\".\"additional_filters\""},
	SearchCount:       whereHelpernull_Int{field: "\"search_logs\".\"search_count\""},
	CreatedAt:         whereHelpernull_Time{field: "\"search_logs\".\"created_at\""},
	UpdatedAt:         whereHelpernull_Time{field: "\"search_logs\".\"updated_at\""},
}

// SearchLogRels is where relationship names are stored.
var SearchLogRels = struct {
	Location string
	User     string
}{
	Location: "Location",
	User:     "User",
}

// searchLogR is where relationships are stored.
type searchLogR struct {
	Location *Address `boil:"Location" json:"Location" toml:"Location" yaml:"Location"`
	User     *User    `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*searchLogR) NewStruct() *searchLogR {
	return &searchLogR{}
}

func (o *SearchLog) GetLocation() *Address {
	if o == nil {
		return nil
	}

	return o.R.GetLocation()
}

func (r *searchLogR) GetLocation() *Address {
	if r == nil {
		return nil
	}

	return r.Location
}

func (o *SearchLog) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *searchLogR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// searchLogL is where Load methods for each relationship are stored.
type searchLogL struct{}

var (
	searchLogAllColumns            = []string{"id", "user_id", "keyword", "location_id", "min_price", "max_price", "min_area_m2", "max_area_m2", "num_bedrooms", "num_bathrooms", "num_floors", "property_type", "pet_allowed", "has_balcony", "has_parking", "additional_filters", "search_count", "created_at", "updated_at"}
	searchLogColumnsWithoutDefault = []string{}
	searchLogColumnsWithDefault    = []string{"id", "user_id", "keyword", "location_id", "min_price", "max_price", "min_area_m2", "max_area_m2", "num_bedrooms", "num_bathrooms", "num_floors", "property_type", "pet_allowed", "has_balcony", "has_parking", "additional_filters", "search_count", "created_at", "updated_at"}
	searchLogPrimaryKeyColumns     = []string{"id"}
	searchLogGeneratedColumns      = []string{"id"}
)

type (
	// SearchLogSlice is an alias for a slice of pointers to SearchLog.
	// This should almost always be used instead of []SearchLog.
	SearchLogSlice []*SearchLog
	// SearchLogHook is the signature for custom SearchLog hook methods
	SearchLogHook func(context.Context, boil.ContextExecutor, *SearchLog) error

	searchLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	searchLogType                 = reflect.TypeOf(&SearchLog{})
	searchLogMapping              = queries.MakeStructMapping(searchLogType)
	searchLogPrimaryKeyMapping, _ = queries.BindMapping(searchLogType, searchLogMapping, searchLogPrimaryKeyColumns)
	searchLogInsertCacheMut       sync.RWMutex
	searchLogInsertCache          = make(map[string]insertCache)
	searchLogUpdateCacheMut       sync.RWMutex
	searchLogUpdateCache          = make(map[string]updateCache)
	searchLogUpsertCacheMut       sync.RWMutex
	searchLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var searchLogAfterSelectMu sync.Mutex
var searchLogAfterSelectHooks []SearchLogHook

var searchLogBeforeInsertMu sync.Mutex
var searchLogBeforeInsertHooks []SearchLogHook
var searchLogAfterInsertMu sync.Mutex
var searchLogAfterInsertHooks []SearchLogHook

var searchLogBeforeUpdateMu sync.Mutex
var searchLogBeforeUpdateHooks []SearchLogHook
var searchLogAfterUpdateMu sync.Mutex
var searchLogAfterUpdateHooks []SearchLogHook

var searchLogBeforeDeleteMu sync.Mutex
var searchLogBeforeDeleteHooks []SearchLogHook
var searchLogAfterDeleteMu sync.Mutex
var searchLogAfterDeleteHooks []SearchLogHook

var searchLogBeforeUpsertMu sync.Mutex
var searchLogBeforeUpsertHooks []SearchLogHook
var searchLogAfterUpsertMu sync.Mutex
var searchLogAfterUpsertHooks []SearchLogHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SearchLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SearchLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SearchLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SearchLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SearchLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SearchLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SearchLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SearchLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SearchLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSearchLogHook registers your hook function for all future operations.
func AddSearchLogHook(hookPoint boil.HookPoint, searchLogHook SearchLogHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		searchLogAfterSelectMu.Lock()
		searchLogAfterSelectHooks = append(searchLogAfterSelectHooks, searchLogHook)
		searchLogAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		searchLogBeforeInsertMu.Lock()
		searchLogBeforeInsertHooks = append(searchLogBeforeInsertHooks, searchLogHook)
		searchLogBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		searchLogAfterInsertMu.Lock()
		searchLogAfterInsertHooks = append(searchLogAfterInsertHooks, searchLogHook)
		searchLogAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		searchLogBeforeUpdateMu.Lock()
		searchLogBeforeUpdateHooks = append(searchLogBeforeUpdateHooks, searchLogHook)
		searchLogBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		searchLogAfterUpdateMu.Lock()
		searchLogAfterUpdateHooks = append(searchLogAfterUpdateHooks, searchLogHook)
		searchLogAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		searchLogBeforeDeleteMu.Lock()
		searchLogBeforeDeleteHooks = append(searchLogBeforeDeleteHooks, searchLogHook)
		searchLogBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		searchLogAfterDeleteMu.Lock()
		searchLogAfterDeleteHooks = append(searchLogAfterDeleteHooks, searchLogHook)
		searchLogAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		searchLogBeforeUpsertMu.Lock()
		searchLogBeforeUpsertHooks = append(searchLogBeforeUpsertHooks, searchLogHook)
		searchLogBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		searchLogAfterUpsertMu.Lock()
		searchLogAfterUpsertHooks = append(searchLogAfterUpsertHooks, searchLogHook)
		searchLogAfterUpsertMu.Unlock()
	}
}

// One returns a single searchLog record from the query.
func (q searchLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SearchLog, error) {
	o := &SearchLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for search_logs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SearchLog records from the query.
func (q searchLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (SearchLogSlice, error) {
	var o []*SearchLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SearchLog slice")
	}

	if len(searchLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SearchLog records in the query.
func (q searchLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count search_logs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q searchLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if search_logs exists")
	}

	return count > 0, nil
}

// Location pointed to by the foreign key.
func (o *SearchLog) Location(mods ...qm.QueryMod) addressQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LocationID),
	}

	queryMods = append(queryMods, mods...)

	return Addresses(queryMods...)
}

// User pointed to by the foreign key.
func (o *SearchLog) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadLocation allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (searchLogL) LoadLocation(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSearchLog interface{}, mods queries.Applicator) error {
	var slice []*SearchLog
	var object *SearchLog

	if singular {
		var ok bool
		object, ok = maybeSearchLog.(*SearchLog)
		if !ok {
			object = new(SearchLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSearchLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSearchLog))
			}
		}
	} else {
		s, ok := maybeSearchLog.(*[]*SearchLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSearchLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSearchLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &searchLogR{}
		}
		if !queries.IsNil(object.LocationID) {
			args[object.LocationID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &searchLogR{}
			}

			if !queries.IsNil(obj.LocationID) {
				args[obj.LocationID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`addresses`),
		qm.WhereIn(`addresses.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Address")
	}

	var resultSlice []*Address
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Address")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for addresses")
	}

	if len(addressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Location = foreign
		if foreign.R == nil {
			foreign.R = &addressR{}
		}
		foreign.R.LocationSearchLogs = append(foreign.R.LocationSearchLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.LocationID, foreign.ID) {
				local.R.Location = foreign
				if foreign.R == nil {
					foreign.R = &addressR{}
				}
				foreign.R.LocationSearchLogs = append(foreign.R.LocationSearchLogs, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (searchLogL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSearchLog interface{}, mods queries.Applicator) error {
	var slice []*SearchLog
	var object *SearchLog

	if singular {
		var ok bool
		object, ok = maybeSearchLog.(*SearchLog)
		if !ok {
			object = new(SearchLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSearchLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSearchLog))
			}
		}
	} else {
		s, ok := maybeSearchLog.(*[]*SearchLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSearchLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSearchLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &searchLogR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &searchLogR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SearchLogs = append(foreign.R.SearchLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SearchLogs = append(foreign.R.SearchLogs, local)
				break
			}
		}
	}

	return nil
}

// SetLocation of the searchLog to the related item.
// Sets o.R.Location to related.
// Adds o to related.R.LocationSearchLogs.
func (o *SearchLog) SetLocation(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Address) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"search_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"location_id"}),
		strmangle.WhereClause("\"", "\"", 2, searchLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.LocationID, related.ID)
	if o.R == nil {
		o.R = &searchLogR{
			Location: related,
		}
	} else {
		o.R.Location = related
	}

	if related.R == nil {
		related.R = &addressR{
			LocationSearchLogs: SearchLogSlice{o},
		}
	} else {
		related.R.LocationSearchLogs = append(related.R.LocationSearchLogs, o)
	}

	return nil
}

// RemoveLocation relationship.
// Sets o.R.Location to nil.
// Removes o from all passed in related items' relationships struct.
func (o *SearchLog) RemoveLocation(ctx context.Context, exec boil.ContextExecutor, related *Address) error {
	var err error

	queries.SetScanner(&o.LocationID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("location_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Location = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.LocationSearchLogs {
		if queries.Equal(o.LocationID, ri.LocationID) {
			continue
		}

		ln := len(related.R.LocationSearchLogs)
		if ln > 1 && i < ln-1 {
			related.R.LocationSearchLogs[i] = related.R.LocationSearchLogs[ln-1]
		}
		related.R.LocationSearchLogs = related.R.LocationSearchLogs[:ln-1]
		break
	}
	return nil
}

// SetUser of the searchLog to the related item.
// Sets o.R.User to related.
// Adds o to related.R.SearchLogs.
func (o *SearchLog) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"search_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, searchLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &searchLogR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			SearchLogs: SearchLogSlice{o},
		}
	} else {
		related.R.SearchLogs = append(related.R.SearchLogs, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *SearchLog) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.SearchLogs {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.SearchLogs)
		if ln > 1 && i < ln-1 {
			related.R.SearchLogs[i] = related.R.SearchLogs[ln-1]
		}
		related.R.SearchLogs = related.R.SearchLogs[:ln-1]
		break
	}
	return nil
}

// SearchLogs retrieves all the records using an executor.
func SearchLogs(mods ...qm.QueryMod) searchLogQuery {
	mods = append(mods, qm.From("\"search_logs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"search_logs\".*"})
	}

	return searchLogQuery{q}
}

// FindSearchLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSearchLog(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*SearchLog, error) {
	searchLogObj := &SearchLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"search_logs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, searchLogObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from search_logs")
	}

	if err = searchLogObj.doAfterSelectHooks(ctx, exec); err != nil {
		return searchLogObj, err
	}

	return searchLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SearchLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no search_logs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	searchLogInsertCacheMut.RLock()
	cache, cached := searchLogInsertCache[key]
	searchLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			searchLogAllColumns,
			searchLogColumnsWithDefault,
			searchLogColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, searchLogGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(searchLogType, searchLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(searchLogType, searchLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"search_logs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"search_logs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into search_logs")
	}

	if !cached {
		searchLogInsertCacheMut.Lock()
		searchLogInsertCache[key] = cache
		searchLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SearchLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SearchLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	searchLogUpdateCacheMut.RLock()
	cache, cached := searchLogUpdateCache[key]
	searchLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			searchLogAllColumns,
			searchLogPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, searchLogGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update search_logs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"search_logs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, searchLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(searchLogType, searchLogMapping, append(wl, searchLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update search_logs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for search_logs")
	}

	if !cached {
		searchLogUpdateCacheMut.Lock()
		searchLogUpdateCache[key] = cache
		searchLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q searchLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for search_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for search_logs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SearchLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"search_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, searchLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in searchLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all searchLog")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SearchLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no search_logs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	searchLogUpsertCacheMut.RLock()
	cache, cached := searchLogUpsertCache[key]
	searchLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			searchLogAllColumns,
			searchLogColumnsWithDefault,
			searchLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			searchLogAllColumns,
			searchLogPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, searchLogGeneratedColumns)
		update = strmangle.SetComplement(update, searchLogGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert search_logs, could not build update column list")
		}

		ret := strmangle.SetComplement(searchLogAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(searchLogPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert search_logs, could not build conflict column list")
			}

			conflict = make([]string, len(searchLogPrimaryKeyColumns))
			copy(conflict, searchLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"search_logs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(searchLogType, searchLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(searchLogType, searchLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert search_logs")
	}

	if !cached {
		searchLogUpsertCacheMut.Lock()
		searchLogUpsertCache[key] = cache
		searchLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SearchLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SearchLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SearchLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), searchLogPrimaryKeyMapping)
	sql := "DELETE FROM \"search_logs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from search_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for search_logs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q searchLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no searchLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from search_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for search_logs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SearchLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(searchLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"search_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, searchLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from searchLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for search_logs")
	}

	if len(searchLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SearchLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSearchLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SearchLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SearchLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"search_logs\".* FROM \"search_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, searchLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SearchLogSlice")
	}

	*o = slice

	return nil
}

// SearchLogExists checks if the SearchLog row exists.
func SearchLogExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"search_logs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if search_logs exists")
	}

	return exists, nil
}

// Exists checks if the SearchLog row exists.
func (o *SearchLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SearchLogExists(ctx, exec, o.ID)
}
