version: '3.8'

services:
  db:  # Service PostgreSQL database
    image: postgres:15  # Dùng image postgres phiên bản 15
    restart: always  # Tự động restart nếu container dừng bất ngờ
    environment:  # Các biến môi trường khi khởi động DB
      POSTGRES_USER: postgres  # Tên người dùng mặc định
      POSTGRES_PASSWORD: your_password  # Mật khẩu cho user
      POSTGRES_DB: rental_db  # Tên database khởi tạo sẵn
    ports:
      - "5432:5432"  # Mở port 5432 (host) → 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Gắn volume để lưu dữ liệu vĩnh viễn
    networks:
      - mihome-net  # Nối vào mạng riêng tên "mihome-net"

  app:  # Service Go backend
    build:
      context: ..  # Build từ thư mục cha (giả sử Dockerfile nằm trong ./docker/)
      dockerfile: Dockerfile  # Tên file Dockerfile
    ports:
      - "8080:8080"  # Mở port 8080 (host) → 8080 (container)
    environment:  # Các biến môi trường backend cần để chạy
      DB_HOST: db  # Hostname của service db (Docker DNS sẽ tự nhận)
      DB_PORT: 5432  # Cổng PostgreSQL
      DB_USER: postgres  # Username dùng kết nối DB
      DB_PASSWORD: your_password  # Password kết nối DB
      DB_NAME: rental_db  # Tên DB cần kết nối
      JWT_SECRET: mysecret  # Secret key để mã hóa/giải mã JWT token
    depends_on:
      - db  # Đảm bảo container db khởi động trước
    networks:
      - mihome-net  # Gắn vào cùng mạng với db

volumes:
  postgres_data:  # Khai báo volume để lưu trữ dữ liệu DB

networks:
  mihome-net:  # Khai báo mạng riêng dùng cho các service trong hệ thống
